import { describe, expect, test } from "@jest/globals";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { createEngine } from "@solve-js/api/createEngine";
import { formatValue } from "@solve-js/format/FormatEngine";
import { DEFAULT_FORMATTING_SETTINGS } from "@solve-js/format/FormattingSettings";

/**
 * #782: the generated unit reference headed its rows and base sentences with
 * whichever spelling came first in the table, which is the American one
 * (`meter`) or an internal code (`mps`). `scripts/lib/unit-names.mjs` now picks
 * by preference: a readable name for a code, the British spelling where the row
 * carries it, and the first spelling otherwise; a measure with no unit of size 1
 * names its base. The helpers are ES modules the jest transform does not load,
 * so they are called through a child `node`. The page itself is regenerated by
 * `npm run stats:units` and held by `lint:units`.
 */

const LIB = path.resolve(__dirname, "../../../../scripts/lib/unit-names.mjs");
const GENERATOR = path.resolve(__dirname, "../../../../scripts/generate-unit-reference.mjs");

/** Runs a snippet with the module's exports in scope as `lib`, and returns its JSON output. */
function withLib(body: string): unknown {
	const program = `import * as lib from ${JSON.stringify(`file://${LIB}`)};
const out = (() => { ${body} })();
process.stdout.write(JSON.stringify(out));`;
	const result = spawnSync(process.execPath, ["--input-type=module", "-e", program], { encoding: "utf8", timeout: 30_000 });
	if (result.status !== 0) throw new Error(result.stderr);
	return JSON.parse(result.stdout);
}

const headlines = (rows: string[][]): unknown =>
	withLib(`const namer = lib.unitNamer(); return ${JSON.stringify(rows)}.map((row) => namer.headline(row));`);

describe("the headline a row is given", () => {
	test("the British spelling where the row carries it (the issue's rows)", () => {
		expect(
			headlines([
				["meter", "metre", "meters", "metres", "m"],
				["square meter", "square metre", "m2"],
				["cubic meter", "cubic metre", "m3"],
				["kilometer", "kilometre", "km"],
				["liter", "liters", "litre", "litres", "l"],
			]),
		).toEqual(["metre", "square metre", "cubic metre", "kilometre", "litre"]);
	});

	test("a readable name over a code (the issue's rows)", () => {
		expect(headlines([["mps"], ["m3s"], ["kmpl"], ["min_km"], ["ft_s"]])).toEqual([
			"metre per second",
			"cubic metre per second",
			"kilometre per litre",
			"minute per kilometre",
			"foot per second",
		]);
	});

	test("the first spelling when there is no British form and no display name", () => {
		expect(headlines([["foot", "feet", "ft"], ["gram", "grams", "g"], ["ton", "tons"]])).toEqual(["foot", "gram", "ton"]);
	});

	test("a British form that is not among the row's spellings is not invented", () => {
		// `cubic kilometre` is not a spelling the tables carry, so a headline of
		// it would name something the reader cannot type.
		expect(headlines([["cubic kilometer", "cubic kilometers", "km3"]])).toEqual(["cubic kilometer"]);
	});

	test("a display name applies only when the code heads the row", () => {
		expect(headlines([["knot", "mps"]])).toEqual(["knot"]);
	});
});

describe("britishSpelling", () => {
	test("ordinary: the two stems that differ", () => {
		expect(withLib(`return ["meter", "kilometers", "liter", "milliliters", "candela per square meter"].map(lib.britishSpelling);`)).toEqual([
			"metre",
			"kilometres",
			"litre",
			"millilitres",
			"candela per square metre",
		]);
	});

	test("boundary: an empty spelling, one already British, and words the stems do not touch", () => {
		expect(withLib(`return ["", "metre", "ton", "gram", "M", "m"].map(lib.britishSpelling);`)).toEqual(["", "metre", "ton", "gram", "M", "m"]);
	});

	test("hostile: prototype words, markup and look-alike characters pass through as text", () => {
		expect(withLib(`return ["constructor", "__proto__", "<b>meter</b>", "met\\u200ber", "m\\u0435ter"].map(lib.britishSpelling);`)).toEqual([
			"constructor",
			"__proto__",
			"<b>metre</b>",
			"met​er",
			"mеter",
		]);
	});
});

describe("the display-name and base tables", () => {
	test("a spelling named after an inherited property is not read as listed", () => {
		expect(headlines([["constructor"], ["toString"], ["__proto__"], ["hasOwnProperty"]])).toEqual(["constructor", "toString", "__proto__", "hasOwnProperty"]);
		expect(withLib(`return ["constructor", "toString", "__proto__"].map((k) => lib.UNNAMED_BASES.has(k));`)).toEqual([false, false, false]);
		expect(withLib(`lib.unitNamer().headline(["__proto__"]); return Object.getOwnPropertyNames(Object.prototype).length;`)).toBe(
			Object.getOwnPropertyNames(Object.prototype).length,
		);
	});

	test("every display name is words, in British spelling, and no code is its own name", () => {
		const entries = withLib(`return [...lib.DISPLAY_NAMES];`) as Array<[string, string]>;
		expect(entries.length).toBeGreaterThan(0);
		for (const [code, name] of entries) {
			expect(name).not.toBe(code);
			expect(name).toMatch(/^[A-Za-z0-9 -]+$/);
			expect(name).not.toMatch(/meter|liter/);
		}
	});

	test("the pace, reactive power, fuel consumption and parts-per measures name a base", () => {
		expect(withLib(`return ["pace", "reactivePower", "fuelConsumption", "partsPer"].map((k) => lib.UNNAMED_BASES.get(k));`)).toEqual([
			"second per metre",
			"var",
			"litre per kilometre",
			"whole",
		]);
	});

	test("a namer reports the display names it never used, and each namer keeps its own record", () => {
		const out = withLib(`
			const a = lib.unitNamer();
			a.headline(["mps"]);
			const b = lib.unitNamer();
			return { a: a.unusedDisplayNames().includes("mps"), aOthers: a.unusedDisplayNames().includes("kmpl"), b: b.unusedDisplayNames().includes("mps") };
		`);
		expect(out).toEqual({ a: false, aOthers: true, b: true });
	});

	test("a thousand-row measure is named promptly", () => {
		const started = Date.now();
		const rows = Array.from({ length: 1000 }, (_, i) => [`x${i}meter`, `x${i}metre`]);
		const out = headlines(rows) as string[];
		expect(out[999]).toBe("x999metre");
		expect(Date.now() - started).toBeLessThan(20_000);
	});
});

describe("the generator uses the names", () => {
	const source = fs.readFileSync(GENERATOR, "utf8");

	test("it takes the headline and the unnamed bases from the shared module", () => {
		expect(source).toContain('import { UNNAMED_BASES, unitNamer } from "./lib/unit-names.mjs";');
		expect(source).not.toMatch(/function headline\(spellings\)\s*\{\s*return spellings\[0\];/);
	});

	test("it fails rather than writing a section with no base sentence, or a stale display name", () => {
		expect(source).toContain("Name its base in UNNAMED_BASES.");
		expect(source).toContain("DISPLAY_NAMES names spellings that head no row");
	});
});

describe("what the page claims about spellings is what the engine does", () => {
	const engine = createEngine({ locale: "en", config: { network: { enabled: false } } });
	const show = (line: string): string => formatValue(engine.evaluateLine(1, line), DEFAULT_FORMATTING_SETTINGS).replace(/^=\s*/, "");

	test("both spellings are read, and each answer shows back what was typed", () => {
		expect(show("5 metre")).toBe("5.00 metre");
		expect(show("5 meter")).toBe("5.00 meter");
		expect(show("3 m/s")).toBe("3.00 m/s");
		expect(show("1 mps")).toBe("1.00 mps");
	});

	test("the codes the display names cover are each a unit the engine reads", () => {
		const codes = withLib(`return [...lib.DISPLAY_NAMES.keys()];`) as string[];
		for (const code of codes) {
			const value = engine.evaluateLine(1, `1 ${code}`);
			expect([code, value.unit]).toEqual([code, code]);
		}
	});
});
