import { afterEach, describe, expect, test } from "@jest/globals";
import * as fs from "node:fs";
import * as path from "node:path";
import { newTrackedEngine } from "@tools/trackedEngine";
import { RecordingCalendar } from "@tools/recordingCalendar";
import { REPO_ROOT, callExport, removeTempTrees, runScript, tempTree } from "@tools/scriptHarness";
import { PROTOTYPE_WORDS, NUMERIC_EDGES, TEXT_EDGES, expectHonestDocument, expectHonestLine, expectPrototypeUntouched, fill } from "@tools/adversarial";
import { dateCalendarInZone } from "@solve-js/calendar/DateCalendar";
import { formatValue } from "@solve-js/format/FormatEngine";
import { currencyExchangeService } from "@solve-js/uom/CurrencyExchange";
import { numberValue, uomValue, errorValue, pendingValue, percentageValue } from "@solve-js/vm/Value";
import { UK_CPI_TABLE, UK_CPI_MIN_YEAR, UK_CPI_MAX_YEAR, UK_CPI_PARTIAL_YEAR } from "@solve-js/packages/finance/data/UkCpiTable";
import { EURO_HICP_TABLE, EURO_HICP_MIN_YEAR, EURO_HICP_MAX_YEAR, EURO_HICP_PARTIAL_YEAR, EURO_FIRST_YEAR } from "@solve-js/packages/finance/data/EuroHicpTable";
import {
	US_PRICE_INDEX,
	UK_PRICE_INDEX,
	EURO_PRICE_INDEX,
	INDEXED_CURRENCIES,
	priceIndexFor,
	indexFigure,
	indexRatio,
	yearOutsideIndex,
} from "@solve-js/packages/finance/data/PriceIndices";
import { adjustByCurrency, inflationIndexFor, isPriceIndex } from "@solve-js/packages/finance/data/InflationAmount";

/**
 * Issue #756: the inflation forms read one table, the US CPI-U, whatever the
 * amount's currency, so `what is £100 from 1990` was £254.55, the American
 * figure with a pound sign (refused since #650). The amount's currency now
 * picks the index: US dollars read the BLS CPI-U (#700), pounds sterling the
 * ONS long-term indicator of consumer prices, series CDKO, and euros the
 * euro-area HICP, from the ECB's monthly series ICP.M.U2.N.000000.4.INX. Each
 * table is generated by a script from a recorded snapshot, in #700's shape.
 *
 * The boundary: CDKO is the ONS's own long-run series, which chains RPI-era
 * data before the CPI's start; it is none of CPI, CPIH or RPI alone. The
 * euro-area index starts in 1996 but the euro in 1999, so a euro year before
 * 1999 is refused, and the ECB's series ends with December 2025 (the dataset
 * was discontinued in February 2026), so a euro line that runs to 2026 is
 * refused. Every other currency keeps a refusal, and so does a bare number.
 */

afterEach(() => {
	removeTempTrees();
	currencyExchangeService.clearRates();
});

const UK = "build-uk-cpi-table.mjs";
const EURO = "build-euro-hicp-table.mjs";
const ALL = "build-price-indices.mjs";
const FIXTURES = path.join(REPO_ROOT, "scripts/fixtures/cpi");
const UK_ANNUAL_TEXT = fs.readFileSync(path.join(FIXTURES, "cpi-uk-annual.csv"), "utf8");
const UK_MONTHLY_TEXT = fs.readFileSync(path.join(FIXTURES, "cpi-uk-monthly.csv"), "utf8");
const ECB_TEXT = fs.readFileSync(path.join(FIXTURES, "ecb-icp-hicp-euro-area.csv"), "utf8");
const UK_TABLE_FILE = path.join(REPO_ROOT, "packages/engine/src/packages/finance/data/UkCpiTable.ts");
const EURO_TABLE_FILE = path.join(REPO_ROOT, "packages/engine/src/packages/finance/data/EuroHicpTable.ts");

/** 11 March 2026, noon UTC: the clock the docs examples run on, so a present-year line has a fixed answer. */
const NOW_2026 = Date.UTC(2026, 2, 11, 12, 0, 0);

function engine2026() {
	return newTrackedEngine({ calendar: new RecordingCalendar(NOW_2026, dateCalendarInZone("UTC")) });
}

function shown(line: string): string {
	return formatValue(engine2026().evaluateExpression(line));
}

function code(line: string): string | undefined {
	return engine2026().evaluateExpression(line).errorCode;
}

interface Annual { year: number; value: number; decimals: number }
interface Monthly { year: number; month: number; value: number; decimals: number }
interface Series { years: Array<{ year: number; value: number; decimals: number; months: number; source?: string }>; partial: { year: number; months: number[] } | null }

/** The script's message for a call expected to be refused, or "" when it was not. */
function refusal(script: string, exportName: string, args: readonly unknown[]): string {
	try {
		callExport(script, exportName, args);
		return "";
	} catch (error) {
		return String((error as Error).message);
	}
}

/** A CSV's data rows changed: `edit` maps each row to its replacement, a list of rows, or null to drop it. */
function edited(text: string, edit: (line: string) => string | null | string[]): string {
	const [header, ...rows] = text.trimEnd().split("\n");
	const out: string[] = [header];
	for (const row of rows) {
		const next = edit(row);
		if (next === null) continue;
		if (Array.isArray(next)) out.push(...next);
		else out.push(next);
	}
	return `${out.join("\n")}\n`;
}

const ONS_MONTHS = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];

/**
 * The recorded figures in the ONS generator's CSV shape: a metadata block,
 * then every period quoted, years first, then quarters, then months, as the
 * generator writes it. Built from the recording, since this environment
 * cannot reach www.ons.gov.uk; the shape is the generator's.
 */
function onsCsv(cdid = "CDKO"): string {
	const lines = [
		'"Title","Long term indicator of prices of consumer goods and services: Jan 1974=100"',
		`"CDID","${cdid}"`,
		'"Source dataset ID","MM23"',
		'"PreUnit",""',
		'"Unit","Index, base year = 100"',
		'"Release date","17-09-2026"',
		'"Next release","21 October 2026"',
		'"Important notes",""',
	];
	for (const row of UK_ANNUAL_TEXT.trimEnd().split("\n").slice(1)) {
		const [year, value] = row.split(",");
		lines.push(`"${year}","${value}"`);
	}
	lines.push('"1947 Q3","29.2"');
	for (const row of UK_MONTHLY_TEXT.trimEnd().split("\n").slice(1)) {
		const [date, value] = row.split(",");
		lines.push(`"${date.slice(0, 4)} ${ONS_MONTHS[Number(date.slice(5, 7)) - 1]}","${value}"`);
	}
	return `${lines.join("\n")}\n`;
}

describe("the lines from the issue", () => {
	test.each([
		["what was $500 worth in 1990", "= $197.32"],
		["what is £100 from 1990", "= £327.52"],
		["what is 100 GBP from 1990", "= £327.52"],
	])("%s", (line, expected) => {
		expect(shown(line)).toBe(expected);
	});

	test("what is €100 from 1990 has no honest answer, and says why", () => {
		expect(shown("what is €100 from 1990")).toBe(
			"Year 1990 is before the euro began in 1999, so there is no amount in euros from then to adjust (the euro-area price index itself starts in 1996)",
		);
		expect(code("what is €100 from 1990")).toBe("INFLATION_YEAR_OUT_OF_RANGE");
	});

	test("the pound reads the UK index in every form", () => {
		expect(shown("what was £500 worth in 1965")).toBe("= £17.92");
		expect(shown("inflationAdjust(£100, 1990, 2020)")).toBe("= £232.44");
		expect(shown("what is £500 in 1990 worth in 2010")).toBe("= £886.33");
		// 1990 is 497.5 and 2020 is 1156.4 in the ONS annual figures.
		expect(engine2026().evaluateExpression("inflationAdjust(£100, 1990, 2020)").toNumber()).toBeCloseTo((100 * 1156.4) / 497.5, 9);
	});

	test("the euro reads the euro-area index where both years are in it", () => {
		expect(shown("inflationAdjust(€100, 2000, 2020)")).toBe("= €138.15");
		expect(shown("what is €100 in 1999 worth in 2025")).toBe("= €172.87");
		expect(shown("inflationAdjust(100 EUR, 2020, 2000)")).toBe("= €72.39");
	});

	test("the dollar is unchanged", () => {
		expect(shown("what is $100 from 1990")).toBe("= $253.39");
		expect(shown("inflationAdjust($100, 1990, 2020)")).toBe("= $198.02");
	});
});

describe("a year before each series starts, and after it ends", () => {
	test("the dollar: 1913 to 2026", () => {
		expect(shown("what is $100 from 1912")).toBe("Year 1912 is outside the bundled CPI table's range (1913-2026)");
	});

	test("the pound: 1800 to 2026", () => {
		expect(UK_CPI_MIN_YEAR).toBe(1800);
		expect(UK_CPI_MAX_YEAR).toBe(2026);
		expect(UK_CPI_TABLE[1800]).toBe(13.5);
		expect(shown("what is £100 from 1800")).toBe("= £12,069.63");
		expect(shown("what is £100 from 1799")).toBe("Year 1799 is outside the bundled UK price index's range (1800-2026)");
		expect(shown("what is £100 from 2027")).toBe("Year 2027 is outside the bundled UK price index's range (1800-2026)");
		for (const line of ["what was £500 worth in 1799", "inflationAdjust(£100, 1700, 2020)", "inflationAdjust(£100, 1990, 2990)", "what is £500 in 1799 worth in 2025"]) {
			expect({ line, code: code(line) }).toEqual({ line, code: "INFLATION_YEAR_OUT_OF_RANGE" });
		}
	});

	test("the euro: the index from 1996, the euro from 1999, the series to 2025", () => {
		expect(EURO_HICP_MIN_YEAR).toBe(1996);
		expect(EURO_FIRST_YEAR).toBe(1999);
		expect(EURO_HICP_MAX_YEAR).toBe(2025);
		expect(EURO_HICP_TABLE[1996]).toBe(71.74);
		expect(shown("inflationAdjust(€100, 1999, 1999)")).toBe("= €100.00");
		for (const year of [1995, 1996, 1997, 1998]) {
			expect(shown(`inflationAdjust(€100, ${year}, 2020)`)).toBe(
				`Year ${year} is before the euro began in 1999, so there is no amount in euros from then to adjust (the euro-area price index itself starts in 1996)`,
			);
		}
		expect(shown("inflationAdjust(€100, 2000, 2026)")).toBe(
			"Year 2026 is outside the bundled euro-area price index's range (1999-2025): the series it is built from ends with 2025, so name a year up to 2025 to adjust to",
		);
	});
});

describe("the current partial year", () => {
	test("the UK table's 2026 is the mean of January to July and is marked partial", () => {
		expect(UK_CPI_PARTIAL_YEAR).toEqual({ year: 2026, months: [1, 2, 3, 4, 5, 6, 7] });
		// January 1603.2 to July 1653.3, as recorded: 11406.1 / 7 = 1629.44.
		expect(UK_CPI_TABLE[2026]).toBe(1629.4);
		expect(UK_CPI_TABLE[2025]).toBe(1588.6);
		expect(shown("inflationAdjust(£100, 2025, 2026)")).toBe("= £102.57");
		expect(fs.readFileSync(UK_TABLE_FILE, "utf8")).toContain("2026 is partial: it averages the 7 months published so far, January to July");
	});

	test("a pound line that runs to the present year reads the partial 2026", () => {
		expect(shown("what is £100 from 2026")).toBe("= £100.00");
		expect(engine2026().evaluateExpression("what is £100 from 2025").toNumber()).toBeCloseTo((100 * 1629.4) / 1588.6, 9);
	});

	test("the euro series has no 2026, so a euro line that runs to the present year is refused", () => {
		expect(EURO_HICP_PARTIAL_YEAR).toBeNull();
		expect(EURO_HICP_TABLE[2026]).toBeUndefined();
		for (const line of ["what is €100 from 2000", "what was €500 worth in 2025", "what is 100 EUR from 2010"]) {
			expect({ line, code: code(line) }).toEqual({ line, code: "INFLATION_YEAR_OUT_OF_RANGE" });
		}
	});

	test("each header states its index, source, retrieval date and method, and the boundary", () => {
		const uk = fs.readFileSync(UK_TABLE_FILE, "utf8");
		expect(uk).toContain("ONS series\n * CDKO, January 1974 = 100");
		expect(uk).toContain("CDKO is the ONS's own long-run consumer price series, which\n * chains RPI-era data before the CPI's start");
		expect(uk).toContain("It is none of CPI, CPIH or RPI on its own.");
		expect(uk).toContain("Retrieved 2026-10-01");
		expect(uk).toContain("Method: each year to 2025 is the annual figure ONS publishes");
		const euro = fs.readFileSync(EURO_TABLE_FILE, "utf8");
		expect(euro).toContain("series\n * ICP.M.U2.N.000000.4.INX");
		expect(euro).toContain("Retrieved 2026-10-01");
		expect(euro).toContain("Method: each year is the mean of its twelve monthly values");
		expect(euro).toContain("the ECB\n * discontinued this dataset in February 2026");
		for (const text of [uk, euro]) expect(text).not.toMatch(/recalled|general knowledge|World Bank|—/);
	});
});

describe("an amount converted between currencies before adjusting, and an amount with no currency", () => {
	test("dollars converted into pounds read the UK index, and pounds into dollars the US one", () => {
		currencyExchangeService.primeRates("USD", { GBP: 0.75, EUR: 0.9 });
		expect(shown("what is ($100 in GBP) from 1990")).toBe("= £245.64");
		expect(shown("inflationAdjust(£100 in USD, 1990, 2020)")).toBe("= $264.03");
		expect(shown("inflationAdjust($100 in EUR, 2000, 2020)")).toBe("= €124.33");
	});

	test("an amount converted into a currency with no index is refused", () => {
		currencyExchangeService.primeRates("USD", { JPY: 150 });
		expect(code("inflationAdjust($100 in JPY, 1990, 2020)")).toBe("INFLATION_NO_INDEX");
	});

	test("a bare number is refused, as the page says, rather than read as dollars", () => {
		expect(shown("what is 100 from 1990")).toBe(
			"a price index measures one currency, and this amount has none: write it with its currency, in US dollars, pounds sterling or euros, such as $100, £100 or €100",
		);
		expect(code("inflationAdjust(100, 1990, 2020)")).toBe("INFLATION_NO_INDEX");
		expect(code("what was 500 worth in 1965")).toBe("INFLATION_NO_INDEX");
	});

	test("other currencies keep a refusal by name", () => {
		expect(shown("what is ¥100 from 1990")).toBe(
			"no price index for JPY is bundled, so there is no record of what it bought in another year: only an amount in US dollars, pounds sterling or euros, such as $100, £100 or €100, can be adjusted",
		);
		for (const line of ["what is 100 CHF from 1990", "inflationAdjust(₹100, 1990, 2020)", "what was 100 AUD worth in 1990"]) {
			expect({ line, code: code(line) }).toEqual({ line, code: "INFLATION_NO_INDEX" });
		}
	});

	test("in <year> dollars asks for dollars, so pounds and euros are pointed at their own form", () => {
		expect(shown("£100 in 1990 dollars")).toBe(
			"in 1990 dollars asks for US dollars, and this amount is in GBP: ask what it was worth in 1990 instead, which reads the UK price index (ONS CDKO)",
		);
		expect(code("€100 in 2000 dollars")).toBe("INFLATION_EXPECTED_USD");
		expect(code("¥100 in 1990 dollars")).toBe("INFLATION_NO_INDEX");
		expect(shown("$100 in 1965 dollars")).toBe("= $9.51");
	});
});

describe("priceIndexFor, indexFigure, indexRatio and yearOutsideIndex", () => {
	test("each indexed currency finds its index, and nothing else does", () => {
		expect(INDEXED_CURRENCIES).toEqual(["USD", "GBP", "EUR"]);
		expect(priceIndexFor("USD")).toBe(US_PRICE_INDEX);
		expect(priceIndexFor("GBP")).toBe(UK_PRICE_INDEX);
		expect(priceIndexFor("EUR")).toBe(EURO_PRICE_INDEX);
		for (const bad of ["gbp", "GBP ", "", "JPY", "XAU", "£", ...PROTOTYPE_WORDS]) {
			expect({ bad, index: priceIndexFor(bad) }).toEqual({ bad, index: undefined });
		}
		expect(priceIndexFor(undefined as unknown as string)).toBeUndefined();
		expect(priceIndexFor(1 as unknown as string)).toBeUndefined();
	});

	test("the indices are frozen", () => {
		expect(Object.isFrozen(UK_PRICE_INDEX)).toBe(true);
		expect(Object.isFrozen(EURO_PRICE_INDEX)).toBe(true);
	});

	test("indexFigure: ordinary, boundary and hostile years", () => {
		expect(indexFigure(UK_PRICE_INDEX, 1990)).toBe(497.5);
		expect(indexFigure(UK_PRICE_INDEX, 1990.9)).toBe(497.5);
		expect(indexFigure(UK_PRICE_INDEX, 1800)).toBe(13.5);
		expect(indexFigure(UK_PRICE_INDEX, 2026)).toBe(1629.4);
		expect(indexFigure(EURO_PRICE_INDEX, 1999)).toBe(74.48);
		expect(indexFigure(EURO_PRICE_INDEX, 2025)).toBe(128.75);
		// In the table, but before the euro.
		expect(indexFigure(EURO_PRICE_INDEX, 1996)).toBeUndefined();
		for (const year of [1799, 2027, Number.NaN, Infinity, -Infinity, -0, 0, -1990, 2 ** 53, Number.MAX_VALUE, Number.MIN_VALUE]) {
			expect({ year, figure: indexFigure(UK_PRICE_INDEX, year) }).toEqual({ year, figure: undefined });
		}
	});

	test("indexRatio and yearOutsideIndex", () => {
		expect(indexRatio(UK_PRICE_INDEX, 1990, 2020)).toBeCloseTo(1156.4 / 497.5, 12);
		expect(indexRatio(EURO_PRICE_INDEX, 2000, 2020)).toBeCloseTo(105.06 / 76.05, 12);
		expect(indexRatio(US_PRICE_INDEX, 1990, 1990)).toBe(1);
		expect(indexRatio(UK_PRICE_INDEX, 1799, 2020)).toBeUndefined();
		expect(indexRatio(EURO_PRICE_INDEX, 2000, 2026)).toBeUndefined();
		expect(yearOutsideIndex(UK_PRICE_INDEX, 1799, 2030)).toBe(1799);
		expect(yearOutsideIndex(UK_PRICE_INDEX, 1990, 2030)).toBe(2030);
		expect(yearOutsideIndex(UK_PRICE_INDEX, 1990, 2020)).toBeUndefined();
		expect(yearOutsideIndex(EURO_PRICE_INDEX, Number.NaN, 2020)).toBeNaN();
	});

	test("each index's refusal names its own range", () => {
		expect(US_PRICE_INDEX.yearOutside(1912)).toBe("Year 1912 is outside the bundled CPI table's range (1913-2026)");
		expect(UK_PRICE_INDEX.yearOutside(1799)).toBe("Year 1799 is outside the bundled UK price index's range (1800-2026)");
		expect(EURO_PRICE_INDEX.yearOutside(1998)).toContain("before the euro began in 1999");
		expect(EURO_PRICE_INDEX.yearOutside(2026)).toContain("(1999-2025)");
	});
});

describe("inflationIndexFor, isPriceIndex and adjustByCurrency", () => {
	test("the currency picks the index", () => {
		expect(inflationIndexFor(uomValue(100, "USD"))).toBe(US_PRICE_INDEX);
		expect(inflationIndexFor(uomValue(100, "GBP"))).toBe(UK_PRICE_INDEX);
		expect(inflationIndexFor(uomValue(100, "EUR"))).toBe(EURO_PRICE_INDEX);
	});

	test("a currency with no index, a quantity, a bare number and a percentage are refused", () => {
		for (const amount of [uomValue(100, "JPY"), uomValue(100, "kg"), numberValue(100), percentageValue(0.1)]) {
			const chosen = inflationIndexFor(amount);
			expect(isPriceIndex(chosen)).toBe(false);
			expect((chosen as { errorCode?: string }).errorCode).toBe("INFLATION_NO_INDEX");
		}
	});

	test("a fault is handed back as it is", () => {
		const fault = errorValue("SOMETHING", "went wrong");
		expect(inflationIndexFor(fault)).toBe(fault);
		const pending = pendingValue("rate");
		expect(inflationIndexFor(pending)).toBe(pending);
	});

	test("a unit that names an inherited property is refused, not looked up", () => {
		for (const word of PROTOTYPE_WORDS) {
			expect(isPriceIndex(inflationIndexFor(uomValue(100, word)))).toBe(false);
		}
	});

	test("adjustByCurrency: an answer, a refused amount and a refused year", () => {
		const ok = adjustByCurrency(uomValue(100, "GBP"), 1990, 2020);
		expect("value" in ok && ok.value).toBeCloseTo((100 * 1156.4) / 497.5, 9);
		const none = adjustByCurrency(uomValue(100, "JPY"), 1990, 2020);
		expect("refused" in none && none.refused.errorCode).toBe("INFLATION_NO_INDEX");
		const early = adjustByCurrency(uomValue(100, "EUR"), 1997, 2020);
		expect("refused" in early && early.refused.errorCode).toBe("INFLATION_YEAR_OUT_OF_RANGE");
		const late = adjustByCurrency(uomValue(100, "GBP"), 1990, 2030);
		expect("refused" in late && late.refused.errorMessage).toBe("Year 2030 is outside the bundled UK price index's range (1800-2026)");
		expect("value" in adjustByCurrency(uomValue(0, "GBP"), 1990, 2020) && adjustByCurrency(uomValue(0, "GBP"), 1990, 2020)).toEqual({ value: 0 });
		const negative = adjustByCurrency(uomValue(-100, "EUR"), 2024, 2025);
		expect("value" in negative && negative.value).toBeCloseTo((-100 * 128.75) / 126.07, 9);
	});
});

describe("the UK generator against the recorded CSVs", () => {
	test("a plain run reproduces the committed table", () => {
		expect(runScript(UK, ["--check"])).toEqual({ status: 0, out: "packages/engine/src/packages/finance/data/UkCpiTable.ts matches its source.\n" });
	});

	test("npm run data:cpi checks all three tables", () => {
		expect(runScript(ALL, ["--check"])).toEqual({
			status: 0,
			out: [
				"packages/engine/src/packages/finance/data/CpiTable.ts matches its source.",
				"packages/engine/src/packages/finance/data/UkCpiTable.ts matches its source.",
				"packages/engine/src/packages/finance/data/EuroHicpTable.ts matches its source.",
				"",
			].join("\n"),
		});
		const scripts = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "package.json"), "utf8")).scripts;
		expect(scripts["data:cpi"]).toBe("node scripts/build-price-indices.mjs");
	});

	test("the recording runs from 1800 (annual) and June 1947 to July 2026 (monthly)", () => {
		const annual = callExport<Annual[]>(UK, "parseAnnualCsv", [UK_ANNUAL_TEXT]);
		expect(annual).toHaveLength(226);
		expect(annual[0]).toEqual({ year: 1800, value: 13.5, decimals: 1 });
		expect(annual[annual.length - 1]).toEqual({ year: 2025, value: 1588.6, decimals: 1 });
		const monthly = callExport<Monthly[]>(UK, "parseMonthlyCsv", [UK_MONTHLY_TEXT]);
		expect(monthly).toHaveLength(950);
		expect(monthly[0]).toEqual({ year: 1947, month: 6, value: 28.9, decimals: 1 });
		expect(monthly[monthly.length - 1]).toEqual({ year: 2026, month: 7, value: 1653.3, decimals: 1 });
	});

	test("every year to 2025 is the published annual figure, and 2026 the mean of its months", () => {
		const series = callExport<Series>(UK, "ukAnnualSeries", [callExport(UK, "parseAnnualCsv", [UK_ANNUAL_TEXT]), callExport(UK, "parseMonthlyCsv", [UK_MONTHLY_TEXT])]);
		expect(series.years).toHaveLength(227);
		// 1993's months average 554.89; ONS publishes 555.1 from the unrounded months.
		expect(series.years.find((y) => y.year === 1993)).toEqual({ year: 1993, value: 555.1, decimals: 1, months: 12, source: "published" });
		expect(series.years.find((y) => y.year === 2026)).toEqual({ year: 2026, value: 1629.4, decimals: 1, months: 7, source: "computed" });
		expect(series.partial).toEqual({ year: 2026, months: [1, 2, 3, 4, 5, 6, 7] });
	});

	test("the ONS generator's CSV and the mirror give the same figures", () => {
		const fromOns = callExport<{ annual: Annual[]; monthly: Monthly[] }>(UK, "parseOnsCsv", [onsCsv()]);
		expect(fromOns.annual).toEqual(callExport(UK, "parseAnnualCsv", [UK_ANNUAL_TEXT]));
		expect(fromOns.monthly).toEqual(callExport(UK, "parseMonthlyCsv", [UK_MONTHLY_TEXT]));
	});

	test("an ONS file for another series, or with no series named, is refused", () => {
		expect(refusal(UK, "parseOnsCsv", [onsCsv("D7BT")])).toContain('CPI_WRONG_SERIES: the file is for series "D7BT", not CDKO');
		expect(refusal(UK, "parseOnsCsv", [onsCsv().replace('"CDID","CDKO"\n', "")])).toContain("CPI_WRONG_SERIES");
		expect(refusal(UK, "parseOnsCsv", [`${onsCsv()}"Notes","x"\n`])).toContain("CPI_CSV_BAD_ROW");
		expect(refusal(UK, "parseOnsCsv", [onsCsv().replace('"2026 JUL","1653.3"', '"2026 JUL","<b>1653.3</b>"')])).toContain("CPI_BAD_INDEX");
	});

	test("toMirrorCsvs writes exactly what the recording holds", () => {
		const files = callExport<{ annual: string; monthly: string }>(UK, "toMirrorCsvs", [callExport(UK, "parseAnnualCsv", [UK_ANNUAL_TEXT]), callExport(UK, "parseMonthlyCsv", [UK_MONTHLY_TEXT])]);
		expect(files).toEqual({ annual: UK_ANNUAL_TEXT, monthly: UK_MONTHLY_TEXT });
	});

	test("a run from a mirror directory to another output splices after the marker and keeps the rest", () => {
		const dir = tempTree({ "cpi-uk-annual.csv": UK_ANNUAL_TEXT, "cpi-uk-monthly.csv": UK_MONTHLY_TEXT, "out.ts": "old\n// END GENERATED BY scripts/build-uk-cpi-table.mjs\n\nexport const KEPT = 1;\n" });
		const result = runScript(UK, [`--from-mirror=${dir}`, `--out=${path.join(dir, "out.ts")}`, "--retrieved=2030-01-02"]);
		expect(result.status).toBe(0);
		const written = fs.readFileSync(path.join(dir, "out.ts"), "utf8");
		expect(written).toContain("Retrieved 2030-01-02");
		expect(written).toContain("export const UK_CPI_MIN_YEAR = 1800;");
		expect(written.endsWith("// END GENERATED BY scripts/build-uk-cpi-table.mjs\n\nexport const KEPT = 1;\n")).toBe(true);
		expect(written).not.toContain("old\n");
	});

	test("a mirror directory with no record of when it was retrieved needs --retrieved", () => {
		const dir = tempTree({ "cpi-uk-annual.csv": UK_ANNUAL_TEXT, "cpi-uk-monthly.csv": UK_MONTHLY_TEXT, "out.ts": "x\n// END GENERATED BY scripts/build-uk-cpi-table.mjs\n" });
		const result = runScript(UK, [`--from-mirror=${dir}`, `--out=${path.join(dir, "out.ts")}`]);
		expect(result.status).toBe(1);
		expect(result.out).toContain("CPI_BAD_RETRIEVED");
	});

	test("the source record: read, refused when malformed, and never read through an inherited property", () => {
		expect(callExport<{ retrieved: string }>(UK, "readSourceFile", [FIXTURES]).retrieved).toBe("2026-10-01");
		const bad = tempTree({ "cpi-uk.source.json": "{ not json" });
		expect(refusal(UK, "readSourceFile", [bad])).toContain("CPI_BAD_SOURCE_FILE: cpi-uk.source.json is not JSON");
		const thin = tempTree({ "cpi-uk.source.json": JSON.stringify({ source: "x" }) });
		expect(refusal(UK, "readSourceFile", [thin])).toContain("CPI_BAD_SOURCE_FILE");
		const proto = tempTree({ "cpi-uk.source.json": '{"__proto__": {"source": "a", "retrieved": "2026-01-01"}}' });
		expect(refusal(UK, "readSourceFile", [proto])).toContain("CPI_BAD_SOURCE_FILE");
	});

	test("--check fails on a table that has drifted from its source", () => {
		const dir = tempTree({ "out.ts": fs.readFileSync(UK_TABLE_FILE, "utf8").replace("1990: 497.5", "1990: 497.6") });
		const result = runScript(UK, ["--check", `--out=${path.join(dir, "out.ts")}`]);
		expect(result.status).toBe(1);
		expect(result.out).toContain("is not what scripts/build-uk-cpi-table.mjs generates. Run npm run data:cpi.");
	});
});

describe("the UK generator's parts", () => {
	const parseBoth = (annual: string, monthly: string) => [callExport(UK, "parseAnnualCsv", [annual]), callExport(UK, "parseMonthlyCsv", [monthly])];

	test("ukAnnualSeries: an annual figure that disagrees with its months beyond rounding is refused", () => {
		const altered = edited(UK_ANNUAL_TEXT, (l) => (l === "1990,497.5" ? "1990,500.0" : l));
		expect(refusal(UK, "ukAnnualSeries", parseBoth(altered, UK_MONTHLY_TEXT))).toContain("CPI_ANNUAL_MISMATCH: 1990 is 500 in the annual figures, but its months average 497.6");
		// Within the tolerance, the published figure stands.
		const close = edited(UK_ANNUAL_TEXT, (l) => (l === "1990,497.5" ? "1990,497.8" : l));
		expect(callExport<Series>(UK, "ukAnnualSeries", parseBoth(close, UK_MONTHLY_TEXT)).years.find((y) => y.year === 1990)!.value).toBe(497.8);
	});

	test("ukAnnualSeries: a missing year, a late start, and holes after the annual figures end are refused", () => {
		expect(refusal(UK, "ukAnnualSeries", parseBoth(edited(UK_ANNUAL_TEXT, (l) => (l.startsWith("1900,") ? null : l)), UK_MONTHLY_TEXT))).toContain("CPI_MISSING_YEAR: 1900 has no annual figure");
		expect(refusal(UK, "ukAnnualSeries", parseBoth(edited(UK_ANNUAL_TEXT, (l) => (l.startsWith("1800,") ? null : l)), UK_MONTHLY_TEXT))).toContain("CPI_MISSING_YEAR: the series starts in 1801");
		expect(refusal(UK, "ukAnnualSeries", parseBoth(UK_ANNUAL_TEXT, edited(UK_MONTHLY_TEXT, (l) => (l.startsWith("2026-03") ? null : l))))).toContain("CPI_MONTH_MISSING: March 2026 is missing");
		const noAnnual2025 = edited(UK_ANNUAL_TEXT, (l) => (l.startsWith("2025,") ? null : l));
		const short2025 = edited(UK_MONTHLY_TEXT, (l) => (l.startsWith("2025-12") ? null : l));
		expect(refusal(UK, "ukAnnualSeries", parseBoth(noAnnual2025, short2025))).toContain("CPI_MONTH_MISSING: 2025 stops in November, but later years have figures");
	});

	test("ukAnnualSeries: a year with only monthly figures that are complete is their mean, and not partial", () => {
		const noAnnual2025 = edited(UK_ANNUAL_TEXT, (l) => (l.startsWith("2025,") ? null : l));
		const series = callExport<Series>(UK, "ukAnnualSeries", parseBoth(noAnnual2025, UK_MONTHLY_TEXT));
		expect(series.years.find((y) => y.year === 2025)).toEqual({ year: 2025, value: 1588.6, decimals: 1, months: 12, source: "computed" });
		expect(series.partial!.year).toBe(2026);
	});

	test("ukAnnualSeries: annual figures alone, with no monthly ones, are every year complete", () => {
		const series = callExport<Series>(UK, "ukAnnualSeries", [callExport(UK, "parseAnnualCsv", [UK_ANNUAL_TEXT]), []]);
		expect(series.years).toHaveLength(226);
		expect(series.partial).toBeNull();
	});

	test("checkAnnual and checkMonthly: order, and refuse an empty list, a bad date and a duplicate", () => {
		expect(callExport<Annual[]>(UK, "checkAnnual", [[{ year: 1801, value: 1, decimals: 0 }, { year: 1800, value: 1, decimals: 0 }]]).map((a) => a.year)).toEqual([1800, 1801]);
		expect(refusal(UK, "checkAnnual", [[]])).toContain("CPI_NO_DATA");
		expect(refusal(UK, "checkAnnual", [null])).toContain("CPI_NO_DATA");
		expect(refusal(UK, "checkAnnual", [[{ year: 1799, value: 1, decimals: 0 }]])).toContain("CPI_BAD_DATE");
		expect(refusal(UK, "checkAnnual", [[{ year: 1800.5, value: 1, decimals: 0 }]])).toContain("CPI_BAD_DATE");
		expect(refusal(UK, "checkAnnual", [[{ year: 1800, value: 1, decimals: 0 }, { year: 1800, value: 2, decimals: 0 }]])).toContain("CPI_DUPLICATE_YEAR: 1800 appears twice");
		expect(callExport(UK, "checkMonthly", [[]])).toEqual([]);
		expect(refusal(UK, "checkMonthly", [null])).toContain("CPI_NO_DATA");
		expect(refusal(UK, "checkMonthly", [[{ year: 1947, month: 13, value: 1, decimals: 0 }]])).toContain("CPI_BAD_DATE");
		expect(refusal(UK, "checkMonthly", [[{ year: 1947, month: 6, value: 1, decimals: 0 }, { year: 1947, month: 6, value: 1, decimals: 0 }]])).toContain("CPI_DUPLICATE_MONTH: 1947-06");
	});

	test("renderTable: the range, the rows and a bad retrieval date refused", () => {
		const series = callExport(UK, "ukAnnualSeries", parseBoth(UK_ANNUAL_TEXT, UK_MONTHLY_TEXT));
		const text = callExport<string>(UK, "renderTable", [series, { source: "a test", retrieved: "2026-10-01" }]);
		expect(text).toContain("export const UK_CPI_MIN_YEAR = 1800;");
		expect(text).toContain("export const UK_CPI_MAX_YEAR = 2026;");
		expect(text).toContain("1800: 13.5, 1801: 15.1,");
		expect(text).toContain("2014: 1010.0,");
		expect(text).toContain("2025: 1588.6, 2026: 1629.4,");
		expect(text.endsWith("// END GENERATED BY scripts/build-uk-cpi-table.mjs")).toBe(true);
		for (const retrieved of ["", "1 October 2026", "__proto__"]) {
			expect(refusal(UK, "renderTable", [series, { source: "a test", retrieved }])).toContain("CPI_BAD_RETRIEVED");
		}
	});

	test("spliceTable keeps what follows the marker, and refuses a file without one", () => {
		expect(callExport(UK, "spliceTable", ["NEW\n// END GENERATED BY scripts/build-uk-cpi-table.mjs", "OLD\n// END GENERATED BY scripts/build-uk-cpi-table.mjs\nrest\n"])).toBe("NEW\n// END GENERATED BY scripts/build-uk-cpi-table.mjs\nrest\n");
		expect(refusal(UK, "spliceTable", ["NEW", "// END GENERATED BY scripts/build-cpi-table.mjs\n"])).toContain("CPI_NO_MARKER");
	});
});

describe("the euro-area generator against the recorded CSV", () => {
	test("a plain run reproduces the committed table", () => {
		expect(runScript(EURO, ["--check"])).toEqual({ status: 0, out: "packages/engine/src/packages/finance/data/EuroHicpTable.ts matches its source.\n" });
	});

	test("the recording is the ECB's series, January 1996 to December 2025", () => {
		const observations = callExport<Monthly[]>(EURO, "parseEcbCsv", [ECB_TEXT]);
		expect(observations).toHaveLength(360);
		expect(observations[0]).toEqual({ year: 1996, month: 1, value: 70.97, decimals: 2 });
		expect(observations[observations.length - 1]).toEqual({ year: 2025, month: 12, value: 129.54, decimals: 2 });
	});

	test("the annual averages are Eurostat's published euro-area annual average index (prc_hicp_aind, INX_A_AVG, CP00, EA)", () => {
		// Eurostat's own export of prc_hicp_aind for geo EA, 2013 to 2022, as
		// published (github.com/pllewy/UE_house_prices_wizualizacja,
		// data/prc_hicp_aind_page_linear.csv). The table computes each year from
		// the ECB's months, so this checks the method against the publisher.
		const published = [99.38, 99.81, 100.0, 100.23, 101.78, 103.56, 104.8, 105.06, 107.78, 116.82];
		const averages = callExport<Series>(EURO, "annualAverages", [callExport(EURO, "parseEcbCsv", [ECB_TEXT])]);
		expect(averages.years.filter((y) => y.year >= 2013 && y.year <= 2022).map((y) => y.value)).toEqual(published);
		expect(averages.years).toHaveLength(30);
		expect(averages.partial).toBeNull();
	});

	test("a series stopping before December has its last year marked partial", () => {
		const short = edited(ECB_TEXT, (l) => (/,2025-(0[4-9]|1[0-2]),/.test(l) ? null : l));
		const averages = callExport<Series>(EURO, "annualAverages", [callExport(EURO, "parseEcbCsv", [short])]);
		expect(averages.partial).toEqual({ year: 2025, months: [1, 2, 3] });
	});

	test("a run from a CSV file to another output, and --check on a drifted table", () => {
		const dir = tempTree({ "in.csv": ECB_TEXT, "out.ts": "old\n// END GENERATED BY scripts/build-euro-hicp-table.mjs\nexport const EURO_FIRST_YEAR = 1999;\n" });
		const result = runScript(EURO, [`--from-csv=${path.join(dir, "in.csv")}`, `--out=${path.join(dir, "out.ts")}`, "--retrieved=2030-01-02"]);
		expect(result.status).toBe(0);
		const written = fs.readFileSync(path.join(dir, "out.ts"), "utf8");
		expect(written).toContain("Retrieved 2030-01-02");
		expect(written.endsWith("// END GENERATED BY scripts/build-euro-hicp-table.mjs\nexport const EURO_FIRST_YEAR = 1999;\n")).toBe(true);
		const drifted = tempTree({ "out.ts": fs.readFileSync(EURO_TABLE_FILE, "utf8").replace("2020: 105.06", "2020: 105.07") });
		const check = runScript(EURO, ["--check", `--out=${path.join(drifted, "out.ts")}`]);
		expect(check.status).toBe(1);
		expect(check.out).toContain("is not what scripts/build-euro-hicp-table.mjs generates. Run npm run data:cpi.");
	});

	test("the source record beside the CSV names where it came from", () => {
		expect(callExport(EURO, "sourceFileFor", ["/a/x.csv"])).toBe("/a/x.source.json");
		const meta = callExport<{ source: string; retrieved: string }>(EURO, "readSourceFile", [path.join(FIXTURES, "ecb-icp-hicp-euro-area.csv")]);
		expect(meta.retrieved).toBe("2026-10-01");
		expect(meta.source).toContain("9bfa365fe6dd664c75f90f271821011bfb8cc5a7e1d0b181850951529e225b88");
	});
});

describe("the euro-area generator's parts", () => {
	test("splitCsv reads quoted cells, doubled quotes, commas and line breaks inside quotes, and CRLF", () => {
		expect(callExport(EURO, "splitCsv", ['a,"b,c",d\r\n1,"say ""hi""",3\n'])).toEqual([["a", "b,c", "d"], ["1", 'say "hi"', "3"]]);
		expect(callExport(EURO, "splitCsv", ['a,"line\none"\n'])).toEqual([["a", "line\none"]]);
		expect(callExport(EURO, "splitCsv", ["a,b"])).toEqual([["a", "b"]]);
		expect(callExport(EURO, "splitCsv", ["\n\n"])).toEqual([]);
		expect(refusal(EURO, "splitCsv", ['a,"never closed\n'])).toContain("CPI_CSV_BAD_ROW: a quoted cell is never closed");
	});

	test("annualAverages refuses a hole in a finished year, a missing year and a late start", () => {
		const parse = (text: string) => callExport(EURO, "parseEcbCsv", [text]);
		expect(refusal(EURO, "annualAverages", [parse(edited(ECB_TEXT, (l) => (l.includes(",2010-06,") ? null : l)))])).toContain("CPI_MONTH_MISSING: June 2010 is missing");
		expect(refusal(EURO, "annualAverages", [parse(edited(ECB_TEXT, (l) => (l.includes(",2005-") ? null : l)))])).toContain("CPI_MISSING_YEAR: 2005 has no monthly values");
		expect(refusal(EURO, "annualAverages", [parse(edited(ECB_TEXT, (l) => (l.includes(",1996-") ? null : l)))])).toContain("CPI_MISSING_YEAR: the series starts in 1997");
	});

	test("checkObservations refuses an empty list, a year before 1996 and a duplicate month", () => {
		expect(refusal(EURO, "checkObservations", [[]])).toContain("CPI_NO_DATA");
		expect(refusal(EURO, "checkObservations", [[{ year: 1995, month: 12, value: 70, decimals: 2 }]])).toContain("CPI_BAD_DATE");
		const one = { year: 1996, month: 1, value: 70, decimals: 2 };
		expect(refusal(EURO, "checkObservations", [[one, one]])).toContain("CPI_DUPLICATE_MONTH: 1996-01 appears twice");
	});

	test("renderTable refuses a bad retrieval date and writes two decimals", () => {
		const averages = callExport(EURO, "annualAverages", [callExport(EURO, "parseEcbCsv", [ECB_TEXT])]);
		const text = callExport<string>(EURO, "renderTable", [averages, { source: "a test", retrieved: "2026-10-01" }]);
		expect(text).toContain("2015: 100.00,");
		expect(text).toContain("export const EURO_HICP_MAX_YEAR = 2025;");
		expect(refusal(EURO, "renderTable", [averages, { source: "a test", retrieved: "soon" }])).toContain("CPI_BAD_RETRIEVED");
	});
});

describe("a malformed or hostile CSV is refused by name", () => {
	const ecbHeader = ECB_TEXT.split("\n")[0];
	const ecbRow = ECB_TEXT.split("\n")[1];

	test.each([
		["an empty annual file", "parseAnnualCsv", "", "CPI_NO_DATA"],
		["whitespace only", "parseAnnualCsv", "  \n\n", "CPI_NO_DATA"],
		["a header and no rows", "parseAnnualCsv", "Year,Price Index\n", "CPI_NO_DATA"],
		["the wrong annual header", "parseAnnualCsv", "year,index\n1800,13.5\n", "CPI_CSV_BAD_HEADER"],
		["a monthly header on the annual file", "parseAnnualCsv", "Date,Price Index\n1800,13.5\n", "CPI_CSV_BAD_HEADER"],
		["a third cell", "parseAnnualCsv", "Year,Price Index\n1800,13.5,x\n", "CPI_CSV_BAD_ROW"],
		["a year before 1800", "parseAnnualCsv", "Year,Price Index\n1799,13.5\n", "CPI_BAD_DATE"],
		["a two-digit year", "parseAnnualCsv", "Year,Price Index\n99,13.5\n", "CPI_BAD_DATE"],
		["NaN", "parseAnnualCsv", "Year,Price Index\n1800,NaN\n", "CPI_BAD_INDEX"],
		["a negative index", "parseAnnualCsv", "Year,Price Index\n1800,-13.5\n", "CPI_BAD_INDEX"],
		["a zero index", "parseAnnualCsv", "Year,Price Index\n1800,0\n", "CPI_BAD_INDEX"],
		["markup in a cell", "parseAnnualCsv", "Year,Price Index\n1800,<script>alert(1)</script>\n", "CPI_BAD_INDEX"],
		["digits from another script", "parseAnnualCsv", "Year,Price Index\n١٨٠٠,13.5\n", "CPI_BAD_DATE"],
		["a zero-width space in a year", "parseAnnualCsv", "Year,Price Index\n18​00,13.5\n", "CPI_BAD_DATE"],
		["a duplicate year", "parseAnnualCsv", "Year,Price Index\n1800,13.5\n1800,13.6\n", "CPI_DUPLICATE_YEAR"],
		["the wrong monthly header", "parseMonthlyCsv", "Date,Index,Inflation\n1947-06-01,28.9,\n", "CPI_CSV_BAD_HEADER"],
		["a date that is not the first", "parseMonthlyCsv", "Date,Price Index\n1947-06-15,28.9\n", "CPI_BAD_DATE"],
		["month 13", "parseMonthlyCsv", "Date,Price Index\n1947-13-01,28.9\n", "CPI_BAD_DATE"],
		["a duplicate month", "parseMonthlyCsv", "Date,Price Index\n1947-06-01,28.9\n1947-06-01,29.0\n", "CPI_DUPLICATE_MONTH"],
		["an exponent", "parseMonthlyCsv", "Date,Price Index\n1947-06-01,2.89e1\n", "CPI_BAD_INDEX"],
		["an ECB file with no OBS_VALUE column", "parseEcbCsv", "KEY,TIME_PERIOD\nICP.M.U2.N.000000.4.INX,1996-01\n", "CPI_CSV_BAD_HEADER"],
		["an ECB row of another series", "parseEcbCsv", `${ecbHeader}\n${ecbRow.replace("ICP.M.U2.N.000000.4.INX", "ICP.M.U2.N.XEF000.4.INX")}\n`, "CPI_WRONG_SERIES"],
		["an ECB row with a cell missing", "parseEcbCsv", `${ecbHeader}\n${ecbRow.replace(/,0$/, "")}\n`, "CPI_CSV_BAD_ROW"],
		["an ECB period that is a quarter", "parseEcbCsv", `${ecbHeader}\n${ecbRow.replace("1996-01", "1996-Q1")}\n`, "CPI_BAD_DATE"],
		["an ECB value with markup", "parseEcbCsv", `${ecbHeader}\n${ecbRow.replace("70.97", "<i>70.97</i>")}\n`, "CPI_BAD_INDEX"],
		["an ECB file with only a header", "parseEcbCsv", `${ecbHeader}\n`, "CPI_NO_DATA"],
		["an empty ECB file", "parseEcbCsv", "", "CPI_NO_DATA"],
	])("%s", (_name, exportName, text, name) => {
		const script = exportName === "parseEcbCsv" ? EURO : UK;
		expect(refusal(script, exportName, [text])).toContain(`${name}:`);
	});

	test.each(PROTOTYPE_WORDS)("%s as a header, a year or a value is refused, not read as a property", (word) => {
		expect(refusal(UK, "parseAnnualCsv", [`Year,${word}\n1800,13.5\n`])).toContain("CPI_CSV_BAD_HEADER");
		expect(refusal(UK, "parseAnnualCsv", [`Year,Price Index\n${word},13.5\n`])).toContain("CPI_BAD_DATE");
		expect(refusal(UK, "parseMonthlyCsv", [`Date,Price Index\n1947-06-01,${word}\n`])).toContain("CPI_BAD_INDEX");
		expect(refusal(EURO, "parseEcbCsv", [`${word},TIME_PERIOD,OBS_VALUE\nICP.M.U2.N.000000.4.INX,1996-01,70.97\n`])).toContain("CPI_CSV_BAD_HEADER");
		expect(refusal(EURO, "parseEcbCsv", [`KEY,TIME_PERIOD,OBS_VALUE\n${word},1996-01,70.97\n`])).toContain("CPI_WRONG_SERIES");
	});

	test("a huge file is refused before it is split", () => {
		expect(refusal(UK, "parseMonthlyCsv", [`Date,Price Index\n${"1947-06-01,28.9\n".repeat(70_000)}`])).toContain("CPI_SOURCE_TOO_LARGE: the source is larger than 1048576 bytes");
		expect(refusal(EURO, "parseEcbCsv", [`KEY,TIME_PERIOD,OBS_VALUE\n${"ICP.M.U2.N.000000.4.INX,1996-01,70.97\n".repeat(60_000)}`])).toContain("CPI_SOURCE_TOO_LARGE");
	});

	test("more rows than the cap are refused, although the file is small", () => {
		const years = Array.from({ length: 401 }, (_, i) => `${1800 + i},13.5`);
		expect(refusal(UK, "parseAnnualCsv", [`Year,Price Index\n${years.join("\n")}\n`])).toContain("CPI_SOURCE_TOO_LARGE: the annual source has 401 rows");
	});

	test("a value that is not text is refused", () => {
		expect(refusal(UK, "parseAnnualCsv", [null])).toContain("CPI_NO_DATA");
		expect(refusal(EURO, "parseEcbCsv", [{ length: 3 }])).toContain("CPI_NO_DATA");
	});

	test("CRLF line endings, a byte-order mark and no trailing newline read the same as the recording", () => {
		const crlf = (text: string) => `﻿${text.trimEnd().split("\n").join("\r\n")}`;
		expect(callExport(UK, "parseAnnualCsv", [crlf(UK_ANNUAL_TEXT)])).toEqual(callExport(UK, "parseAnnualCsv", [UK_ANNUAL_TEXT]));
		expect(callExport(UK, "parseMonthlyCsv", [crlf(UK_MONTHLY_TEXT)])).toEqual(callExport(UK, "parseMonthlyCsv", [UK_MONTHLY_TEXT]));
		expect(callExport(EURO, "parseEcbCsv", [crlf(ECB_TEXT)])).toEqual(callExport(EURO, "parseEcbCsv", [ECB_TEXT]));
	});

	test("the command line refuses a bad file by name, exits 1 and leaves the output untouched", () => {
		const dir = tempTree({ "cpi-uk-annual.csv": "Year,Price Index\n1800,NaN\n", "cpi-uk-monthly.csv": UK_MONTHLY_TEXT, "out.ts": "kept\n// END GENERATED BY scripts/build-uk-cpi-table.mjs\n" });
		const result = runScript(UK, [`--from-mirror=${dir}`, `--out=${path.join(dir, "out.ts")}`, "--retrieved=2026-10-01"]);
		expect(result.status).toBe(1);
		expect(result.out).toContain("CPI_BAD_INDEX: line 2");
		expect(fs.readFileSync(path.join(dir, "out.ts"), "utf8")).toBe("kept\n// END GENERATED BY scripts/build-uk-cpi-table.mjs\n");
	});
});

describe("the data:cpi dispatcher", () => {
	test("one index can be named, and its own options reach only it", () => {
		expect(runScript(ALL, ["--index=uk", "--check"])).toEqual({ status: 0, out: "packages/engine/src/packages/finance/data/UkCpiTable.ts matches its source.\n" });
		const dir = tempTree({ "out.ts": "x\n// END GENERATED BY scripts/build-euro-hicp-table.mjs\n" });
		expect(runScript(ALL, ["--index=euro", `--out=${path.join(dir, "out.ts")}`, "--check"]).status).toBe(1);
	});

	test("a source option without an index, an unknown index and a prototype word are refused", () => {
		expect(runScript(ALL, ["--from-csv=x.csv"]).out).toContain("CPI_OPTION_NEEDS_INDEX: --from-csv=x.csv belongs to one index");
		expect(runScript(ALL, ["--index=jp"]).out).toContain('CPI_UNKNOWN_INDEX: --index takes us, uk, euro, not "jp"');
		for (const word of PROTOTYPE_WORDS) {
			const result = runScript(ALL, [`--index=${word}`, "--check"]);
			expect({ word, status: result.status, refused: result.out.includes("CPI_UNKNOWN_INDEX") }).toEqual({ word, status: 1, refused: true });
		}
	});
});

describe("both document passes agree", () => {
	test("pounds, euros and dollars through parseDocument and evaluateDocument", () => {
		const { batch } = expectHonestDocument(
			[
				"pounds = £100",
				"inflationAdjust(pounds, 1990, 2020)",
				"euros = €100",
				"inflationAdjust(euros, 2000, 2020)",
				"inflationAdjust(euros, 1997, 2020)",
				"inflationAdjust(£100, 1799, 2020)",
				"inflationAdjust(¥100, 1990, 2020)",
				"inflationAdjust($100, 1990, 2020)",
				"start = 1990",
				"inflationAdjust(£100, start, start + 30) - £100",
			].join("\n"),
		);
		expect(batch).toEqual([
			"= £100.00",
			"= £232.44",
			"= €100.00",
			"= €138.15",
			"ERROR Year 1997 is before the euro began in 1999, so there is no amount in euros from then to adjust (the euro-area price index itself starts in 1996)",
			"ERROR Year 1799 is outside the bundled UK price index's range (1800-2026)",
			"ERROR no price index for JPY is bundled, so there is no record of what it bought in another year: only an amount in US dollars, pounds sterling or euros, such as $100, £100 or €100, can be adjusted",
			"= $198.02",
			"= 1,990",
			"= £132.44",
		]);
	});

	test("a CRLF document with a trailing newline", () => {
		const { batch } = expectHonestDocument("inflationAdjust(£100, 1800, 1900)\r\ninflationAdjust(€100, 1999, 2025)\r\n");
		expect(batch.slice(0, 2)).toEqual(["= £68.15", "= €172.87"]);
	});
});

describe("adversarial lines", () => {
	test("prototype words as the currency or the year are honest, and Object.prototype is unchanged", () => {
		expectPrototypeUntouched(() => {
			for (const word of PROTOTYPE_WORDS) {
				expectHonestLine(`what is £100 from ${word}`, { engine: engine2026() });
				expectHonestLine(`inflationAdjust(€100, ${word}, 2020)`);
				expectHonestLine(`inflationAdjust(100 ${word}, 1990, 2020)`);
				expectHonestLine(`what is 100 ${word} from 1990`, { engine: engine2026() });
				expectHonestLine(`100 ${word} in 1990 dollars`, { engine: engine2026() });
			}
		});
	});

	test("numeric edges as the year or the amount are honest, and never a number outside each range", () => {
		for (const line of fill("inflationAdjust(£100, X, 2020)", NUMERIC_EDGES)) expectHonestLine(line, { allowNaN: true });
		for (const line of fill("inflationAdjust(€100, 2000, X)", NUMERIC_EDGES)) expectHonestLine(line, { allowNaN: true });
		for (const line of fill("what was £X worth in 1965", NUMERIC_EDGES)) expectHonestLine(line, { engine: engine2026(), allowNaN: true });
		for (const year of ["0", "-1990", "1799.999", "2^53", "1e308"]) {
			expect({ year, code: code(`inflationAdjust(£100, ${year}, 2020)`) }).toEqual({ year, code: "INFLATION_YEAR_OUT_OF_RANGE" });
			expect({ year, code: code(`inflationAdjust(€100, ${year}, 2020)`) }).toEqual({ year, code: "INFLATION_YEAR_OUT_OF_RANGE" });
		}
	});

	test("zero, negative zero and negative amounts", () => {
		expect(shown("inflationAdjust(£0, 1990, 2020)")).toBe("= £0.00");
		expect(shown("inflationAdjust(-£100, 2024, 2025)")).toBe("= -£104.14");
		expectHonestLine("inflationAdjust(-£0, 1990, 2020)");
	});

	test("text edges around the form are honest", () => {
		for (const text of TEXT_EDGES) expectHonestLine(`what was £500 worth in 1965 ${text}`, { engine: engine2026() });
		for (const text of TEXT_EDGES) expectHonestLine(`inflationAdjust(€100, 2000, 2020) ${text}`);
	});

	test("a long run of inflation lines in every currency stays within its budget", () => {
		const doc = Array.from({ length: 600 }, (_, i) => {
			if (i % 3 === 0) return `inflationAdjust(£100, ${1800 + (i % 227)}, 2026)`;
			if (i % 3 === 1) return `inflationAdjust(€100, ${1999 + (i % 27)}, 2025)`;
			return `inflationAdjust($100, ${1913 + (i % 114)}, 2026)`;
		}).join("\n");
		expectHonestDocument(doc, { budgetMs: 20_000 });
	});

	test("realistic breakage: a typo, the pound's own phrase for dollars, and a value from the line above", () => {
		expect(expectHonestLine("what is £100 form 1990", { engine: engine2026() }).kind).not.toBe("value");
		expect(expectHonestLine("what was £500 worth in 1965x", { engine: engine2026() }).kind).not.toBe("value");
		const { batch } = expectHonestDocument("year = 1999\ninflationAdjust(€1, year, year + 26)");
		expect(batch[1]).toBe("= €1.73");
	});
});
