import { afterEach, describe, expect, test } from "@jest/globals";
import * as fs from "node:fs";
import * as path from "node:path";
import { newTrackedEngine } from "@tools/trackedEngine";
import { RecordingCalendar } from "@tools/recordingCalendar";
import { REPO_ROOT, callExport, removeTempTrees, runScript, tempTree } from "@tools/scriptHarness";
import { PROTOTYPE_WORDS, NUMERIC_EDGES, TEXT_EDGES, expectHonestDocument, expectHonestLine, expectPrototypeUntouched, fill } from "@tools/adversarial";
import { dateCalendarInZone } from "@solve-js/calendar/DateCalendar";
import { formatValue } from "@solve-js/format/FormatEngine";
import {
	CPI_TABLE,
	CPI_MIN_YEAR,
	CPI_MAX_YEAR,
	CPI_PARTIAL_YEAR,
	adjustForInflation,
	getCpi,
	inflationRatio,
} from "@solve-js/packages/finance/data/CpiTable";

/**
 * Issue #700: `what was $500 worth in 1965` was refused, because the bundled
 * price index started in 1970, and the figures it did hold were recalled from
 * general knowledge rather than taken from the published series (2025 read
 * 322.2 against the published 321.943). The table is now generated by
 * `scripts/build-cpi-table.mjs` from BLS series CUUR0000SA0, every year from
 * 1913 to the latest month published, and the CSV it was built from is
 * recorded in `scripts/fixtures/cpi/cpiai.csv`.
 *
 * The boundary: the index is still the US CPI-U, applied only to US dollars
 * (#650; the pound and the euro read their own indices since #756), and inflation still makes no
 * network call when a line is evaluated. The script is a build step.
 */

afterEach(removeTempTrees);

const SCRIPT = "build-cpi-table.mjs";
const FIXTURE = path.join(REPO_ROOT, "scripts/fixtures/cpi/cpiai.csv");
const FIXTURE_TEXT = fs.readFileSync(FIXTURE, "utf8");
const TABLE_FILE = path.join(REPO_ROOT, "packages/engine/src/packages/finance/data/CpiTable.ts");

/** 11 March 2026, noon UTC: the clock the docs examples run on, so a present-year line has a fixed answer. */
const NOW_2026 = Date.UTC(2026, 2, 11, 12, 0, 0);

/** An engine whose present year is 2026 whatever the real clock says. */
function engine2026() {
	return newTrackedEngine({ calendar: new RecordingCalendar(NOW_2026, dateCalendarInZone("UTC")) });
}

function shown(line: string): string {
	return formatValue(engine2026().evaluateExpression(line));
}

function code(line: string): string | undefined {
	return engine2026().evaluateExpression(line).errorCode;
}

interface Observation { year: number; month: number; value: number; decimals: number }
interface YearAverage { year: number; value: number; decimals: number; months: number; source: string }
interface Averages { years: YearAverage[]; partial: { year: number; months: number[] } | null }

/** The script's message for a call expected to be refused, or "" when it was not. */
function refusal(exportName: string, args: readonly unknown[]): string {
	try {
		callExport(SCRIPT, exportName, args);
		return "";
	} catch (error) {
		return String((error as Error).message);
	}
}

/** The fixture with some of its data rows changed: `edit` maps each data line to its replacement (or null to drop it). */
function editedFixture(edit: (line: string) => string | null | string[]): string {
	const [header, ...rows] = FIXTURE_TEXT.trimEnd().split("\n");
	const out: string[] = [header];
	for (const row of rows) {
		const next = edit(row);
		if (next === null) continue;
		if (Array.isArray(next)) out.push(...next);
		else out.push(next);
	}
	return `${out.join("\n")}\n`;
}

/**
 * The fixture's months as BLS public API responses, one per 20-year window as
 * the script asks for them: value text exactly as recorded, October 2025 as the
 * `-` BLS returns for a month it has no value for, and the M13 annual averages
 * the issue quotes for 2024 and 2025. Built from the recorded CSV, since this
 * environment cannot reach api.bls.gov; the shape is the API's documented one.
 */
function blsResponses(): unknown[] {
	const rows = FIXTURE_TEXT.trimEnd().split("\n").slice(1).map((l) => l.split(","));
	const responses: unknown[] = [];
	for (let start = 1913; start <= 2026; start += 20) {
		const end = Math.min(start + 19, 2026);
		const data: unknown[] = [];
		for (const [date, value] of rows) {
			const year = Number(date.slice(0, 4));
			if (year < start || year > end) continue;
			data.push({ year: String(year), period: `M${date.slice(5, 7)}`, periodName: "", value, footnotes: [{}] });
		}
		if (start <= 2025 && end >= 2025) {
			data.push({ year: "2025", period: "M10", periodName: "October", value: "-", footnotes: [{ code: "X", text: "Data unavailable due to the 2025 lapse in appropriations." }] });
			data.push({ year: "2025", period: "M13", periodName: "Annual", value: "321.943", footnotes: [{}] });
			data.push({ year: "2024", period: "M13", periodName: "Annual", value: "313.689", footnotes: [{}] });
		}
		responses.push({ status: "REQUEST_SUCCEEDED", responseTime: 100, message: [], Results: { series: [{ seriesID: "CUUR0000SA0", data }] } });
	}
	return responses;
}

describe("the lines from the issue", () => {
	test("what was $500 worth in 1965 now answers", () => {
		expect(shown("what was $500 worth in 1965")).toBe("= $47.56");
	});

	test.each([
		["what was $500 worth in 1970", "= $58.58"],
		["what was $500 worth in 2025", "= $486.05"],
		["inflationAdjust($100, 1990, 2020)", "= $198.02"],
		["what is $500 in 1990 worth in 2010", "= $834.19"],
		["what is $500 in 1965 worth in 2025", "= $5,110.21"],
		["$100 in 1965 dollars", "= $9.51"],
	])("%s", (line, expected) => {
		expect(shown(line)).toBe(expected);
	});

	test("2025 is the published annual average, not the 322.2 the table had", () => {
		expect(CPI_TABLE[2025]).toBe(321.943);
		expect(CPI_TABLE[2024]).toBe(313.689);
	});
});

describe("the first and last years", () => {
	test("1913 is in the table, the first year of the series", () => {
		expect(CPI_MIN_YEAR).toBe(1913);
		expect(CPI_TABLE[1913]).toBe(9.9);
		expect(shown("what is $100 from 1913")).toBe("= $3,345.25");
		expect(shown("what was $500 worth in 1913")).toBe("= $14.95");
		expect(shown("inflationAdjust($100, 1913, 2026)")).toBe("= $3,345.25");
	});

	test("a year before 1913 is refused by name, in every form", () => {
		for (const line of ["what is $100 from 1912", "what was $500 worth in 1912", "$100 in 1912 dollars", "what is $500 in 1912 worth in 2025", "inflationAdjust($100, 1912, 2020)", "inflationAdjust($100, 1700, 2020)"]) {
			expect({ line, code: code(line) }).toEqual({ line, code: "INFLATION_YEAR_OUT_OF_RANGE" });
		}
		expect(shown("what is $100 from 1912")).toBe("Year 1912 is outside the bundled CPI table's range (1913-2026)");
	});

	test("the last year is the current one, and a year after it is refused", () => {
		expect(CPI_MAX_YEAR).toBe(2026);
		expect(shown("what is $100 from 2026")).toBe("= $100.00");
		expect(shown("what is $100 from 2027")).toBe("Year 2027 is outside the bundled CPI table's range (1913-2026)");
		expect(code("inflationAdjust($100, 1990, 2990)")).toBe("INFLATION_YEAR_OUT_OF_RANGE");
	});

	test("the current year is marked partial with the months it averages", () => {
		expect(CPI_PARTIAL_YEAR).toEqual({ year: 2026, months: [1, 2, 3, 4, 5, 6, 7] });
		// January 325.252 to July 333.918, as recorded.
		expect(CPI_TABLE[2026]).toBe(331.18);
		expect(fs.readFileSync(TABLE_FILE, "utf8")).toContain("2026 is partial: it averages the 7 months published so far, January to July");
	});

	test("the header states the source, the series, the retrieval date and the method, and no longer says the figures were recalled", () => {
		const text = fs.readFileSync(TABLE_FILE, "utf8");
		expect(text).toContain("series CUUR0000SA0");
		expect(text).toContain("Retrieved 2026-10-01");
		expect(text).toContain("Method: each year is the mean of its published monthly values");
		expect(text).toContain("October 2025 was never published");
		expect(text).not.toMatch(/recalled|general knowledge|IMF/);
	});
});

describe("getCpi, inflationRatio and adjustForInflation over the new range", () => {
	test("ordinary years", () => {
		expect(getCpi(1965)).toBe(31.5);
		expect(inflationRatio(1965, 2025)).toBeCloseTo(321.943 / 31.5, 12);
		expect(adjustForInflation(500, 1965, 2025)).toBeCloseTo(5110.206, 3);
	});

	test("the boundaries", () => {
		expect(getCpi(1913)).toBe(9.9);
		expect(getCpi(2026)).toBe(331.18);
		expect(getCpi(1912)).toBeUndefined();
		expect(getCpi(2027)).toBeUndefined();
		expect(getCpi(1913.9)).toBe(9.9);
		expect(inflationRatio(1913, 1913)).toBe(1);
		expect(adjustForInflation(0, 1913, 2026)).toBe(0);
		expect(adjustForInflation(-100, 2024, 2025)).toBeCloseTo(-102.631, 3);
	});

	test("hostile years find nothing rather than an inherited property", () => {
		for (const year of [Number.NaN, Infinity, -Infinity, -0, 0, -1913, 2 ** 53, Number.MAX_VALUE, Number.MIN_VALUE]) {
			expect({ year, cpi: getCpi(year) }).toEqual({ year, cpi: undefined });
		}
		expect(inflationRatio(Number.NaN, 2020)).toBeUndefined();
		expect(adjustForInflation(100, 1990, Infinity)).toBeUndefined();
	});
});

describe("the generator against the recorded CSV", () => {
	test("a plain run reproduces the committed table", () => {
		const result = runScript(SCRIPT, ["--check"]);
		expect(result).toEqual({ status: 0, out: "packages/engine/src/packages/finance/data/CpiTable.ts matches its source.\n" });
	});

	test("the recording runs from January 1913 to July 2026, with October 2025 missing", () => {
		const observations = callExport<Observation[]>(SCRIPT, "parseMirrorCsv", [FIXTURE_TEXT]);
		expect(observations).toHaveLength(1362);
		expect(observations[0]).toEqual({ year: 1913, month: 1, value: 9.8, decimals: 1 });
		expect(observations.find((o) => o.year === 1913 && o.month === 12)!.value).toBe(10);
		expect(observations.find((o) => o.year === 2026 && o.month === 1)!.value).toBe(325.252);
		expect(observations.some((o) => o.year === 2025 && o.month === 10)).toBe(false);
		expect(observations[observations.length - 1]).toEqual({ year: 2026, month: 7, value: 333.918, decimals: 3 });
	});

	test("the missing October is left out of 2025's mean, which gives the published 321.943", () => {
		const averages = callExport<Averages>(SCRIPT, "annualAverages", [callExport(SCRIPT, "parseMirrorCsv", [FIXTURE_TEXT])]);
		const y2025 = averages.years.find((y) => y.year === 2025)!;
		expect(y2025).toEqual({ year: 2025, value: 321.943, decimals: 3, months: 11, source: "computed" });
		expect(averages.years.find((y) => y.year === 2024)!.value).toBe(313.689);
		expect(averages.partial).toEqual({ year: 2026, months: [1, 2, 3, 4, 5, 6, 7] });
		expect(averages.years).toHaveLength(114);
	});

	test("the BLS API path and the mirror path give the same table", () => {
		const fromBls = callExport<{ observations: Observation[]; annual: Record<string, { value: number }> }>(SCRIPT, "parseBlsResponse", [blsResponses()]);
		expect(fromBls.observations).toEqual(callExport(SCRIPT, "parseMirrorCsv", [FIXTURE_TEXT]));
		expect(fromBls.annual).toEqual({ 2024: { value: 313.689, decimals: 3 }, 2025: { value: 321.943, decimals: 3 } });
		const a = callExport<Averages>(SCRIPT, "annualAverages", [fromBls.observations, fromBls.annual]);
		const b = callExport<Averages>(SCRIPT, "annualAverages", [fromBls.observations]);
		expect(a.years.map((y) => y.value)).toEqual(b.years.map((y) => y.value));
		expect(a.years.find((y) => y.year === 2025)!.source).toBe("published");
	});

	test("an M13 figure is not used for the partial year", () => {
		const responses = blsResponses() as Array<{ Results: { series: Array<{ data: unknown[] }> } }>;
		responses[responses.length - 1].Results.series[0].data.push({ year: "2026", period: "M13", value: "999.999" });
		const parsed = callExport<{ observations: Observation[]; annual: object }>(SCRIPT, "parseBlsResponse", [responses]);
		const averages = callExport<Averages>(SCRIPT, "annualAverages", [parsed.observations, parsed.annual]);
		expect(averages.years.find((y) => y.year === 2026)!.value).toBe(331.18);
	});

	test("a run from a CSV file to another output splices after the marker and keeps the rest", () => {
		const dir = tempTree({ "in.csv": FIXTURE_TEXT, "out.ts": "old header\n// END GENERATED BY scripts/build-cpi-table.mjs\n\nexport const KEPT = 1;\n" });
		const result = runScript(SCRIPT, [`--from-csv=${path.join(dir, "in.csv")}`, `--out=${path.join(dir, "out.ts")}`, "--retrieved=2030-01-02"]);
		expect(result.status).toBe(0);
		const written = fs.readFileSync(path.join(dir, "out.ts"), "utf8");
		expect(written).toContain("Retrieved 2030-01-02");
		expect(written).toContain("export const CPI_MIN_YEAR = 1913;");
		expect(written.endsWith("// END GENERATED BY scripts/build-cpi-table.mjs\n\nexport const KEPT = 1;\n")).toBe(true);
		expect(written).not.toContain("old header");
	});

	test("the recorded CSV's source and retrieval date come from the file beside it", () => {
		expect(callExport(SCRIPT, "sourceFileFor", ["/a/cpiai.csv"])).toBe("/a/cpiai.source.json");
		expect(callExport<{ retrieved: string }>(SCRIPT, "readSourceFile", [FIXTURE]).retrieved).toBe("2026-10-01");
		const dir = tempTree({
			"none.csv": "",
			"bad.csv": "",
			"bad.source.json": "{ not json",
			"thin.csv": "",
			"thin.source.json": JSON.stringify({ source: "x" }),
			"proto.csv": "",
			"proto.source.json": '{"__proto__": {"source": "a", "retrieved": "2026-01-01"}}',
		});
		expect(callExport(SCRIPT, "readSourceFile", [path.join(dir, "none.csv")])).toEqual({
			source: "monthly values as mirrored by the Frictionless Data cpi-us dataset (github.com/datasets/cpi-us, data/cpiai.csv)",
		});
		expect(refusal("readSourceFile", [path.join(dir, "bad.csv")])).toContain("CPI_BAD_SOURCE_FILE: bad.source.json is not JSON");
		expect(refusal("readSourceFile", [path.join(dir, "thin.csv")])).toContain("CPI_BAD_SOURCE_FILE");
		expect(refusal("readSourceFile", [path.join(dir, "proto.csv")])).toContain("CPI_BAD_SOURCE_FILE");
	});

	test("a CSV with no record of when it was retrieved needs --retrieved", () => {
		const dir = tempTree({ "in.csv": FIXTURE_TEXT, "out.ts": "x\n// END GENERATED BY scripts/build-cpi-table.mjs\n" });
		const result = runScript(SCRIPT, [`--from-csv=${path.join(dir, "in.csv")}`, `--out=${path.join(dir, "out.ts")}`]);
		expect(result.status).toBe(1);
		expect(result.out).toContain("CPI_BAD_RETRIEVED");
	});

	test("toMirrorCsv writes what parseMirrorCsv reads", () => {
		const observations = callExport<Observation[]>(SCRIPT, "parseMirrorCsv", [FIXTURE_TEXT]);
		const csv = callExport<string>(SCRIPT, "toMirrorCsv", [observations]);
		expect(callExport(SCRIPT, "parseMirrorCsv", [csv])).toEqual(observations);
		expect(csv.split("\n").slice(0, 3)).toEqual(["Date,Index,Inflation", "1913-01-01,9.8,", "1913-02-01,9.8,0.00"]);
	});
});

describe("the generator's parts", () => {
	test("readIndex: ordinary, boundary and hostile values", () => {
		expect(callExport(SCRIPT, "readIndex", ["9.8", "x"])).toEqual({ value: 9.8, decimals: 1 });
		expect(callExport(SCRIPT, "readIndex", [" 325.252 ", "x"])).toEqual({ value: 325.252, decimals: 3 });
		expect(callExport(SCRIPT, "readIndex", ["10", "x"])).toEqual({ value: 10, decimals: 0 });
		for (const bad of ["0", "0.0", "-9.8", "NaN", "Infinity", "1e3", "", " ", "9,8", "+9.8", "9.8.1", "0x10", "٩.٨", "9​.8", "<b>9.8</b>", "1234567.0"]) {
			expect({ bad, message: refusal("readIndex", [bad, "line 2"]) }).toEqual({ bad, message: expect.stringContaining("CPI_BAD_INDEX: line 2") });
		}
	});

	test("roundTo rounds half away from zero at the published precision", () => {
		expect(callExport(SCRIPT, "roundTo", [9.883333, 1])).toBe(9.9);
		expect(callExport(SCRIPT, "roundTo", [207.3425, 3])).toBe(207.343);
		expect(callExport(SCRIPT, "roundTo", [1.005, 2])).toBe(1.01);
		expect(callExport(SCRIPT, "roundTo", [0, 3])).toBe(0);
		expect(callExport(SCRIPT, "roundTo", [331.180428, 3])).toBe(331.18);
	});

	test("checkObservations: sorts, and refuses an empty list, a bad date and a duplicate", () => {
		const ok = [{ year: 1914, month: 1, value: 10, decimals: 1 }, { year: 1913, month: 2, value: 9.8, decimals: 1 }];
		expect(callExport<Observation[]>(SCRIPT, "checkObservations", [ok]).map((o) => o.year)).toEqual([1913, 1914]);
		expect(refusal("checkObservations", [[]])).toContain("CPI_NO_DATA");
		expect(refusal("checkObservations", [null])).toContain("CPI_NO_DATA");
		expect(refusal("checkObservations", [[{ year: 1912, month: 1, value: 9, decimals: 1 }]])).toContain("CPI_BAD_DATE");
		expect(refusal("checkObservations", [[{ year: 1913, month: 13, value: 9, decimals: 1 }]])).toContain("CPI_BAD_DATE");
		expect(refusal("checkObservations", [[{ year: 1913, month: 0, value: 9, decimals: 1 }]])).toContain("CPI_BAD_DATE");
		expect(refusal("checkObservations", [[{ year: 1913.5, month: 1, value: 9, decimals: 1 }]])).toContain("CPI_BAD_DATE");
		expect(refusal("checkObservations", [[ok[0], ok[0]]])).toContain("CPI_DUPLICATE_MONTH: 1914-01 appears twice");
	});

	test("annualAverages: refuses a hole in a finished year, a hole in the partial year, a missing year and a series that starts late", () => {
		const parse = (text: string) => callExport(SCRIPT, "parseMirrorCsv", [text]);
		expect(refusal("annualAverages", [parse(editedFixture((l) => (l.startsWith("1950-06") ? null : l)))])).toContain("CPI_MONTH_MISSING: June 1950 is missing");
		expect(refusal("annualAverages", [parse(editedFixture((l) => (l.startsWith("2026-03") ? null : l)))])).toContain("CPI_MONTH_MISSING: March 2026");
		expect(refusal("annualAverages", [parse(editedFixture((l) => (l.startsWith("1940-") ? null : l)))])).toContain("CPI_MISSING_YEAR: 1940 has no monthly values");
		expect(refusal("annualAverages", [parse(editedFixture((l) => (l.startsWith("1913-") ? null : l)))])).toContain("CPI_MISSING_YEAR: the series starts in 1914");
	});

	test("annualAverages: a known gap must still reproduce the published figure", () => {
		const altered = editedFixture((l) => (l.startsWith("2025-11") ? "2025-11-01,330.000,0.0" : l));
		expect(refusal("annualAverages", [callExport(SCRIPT, "parseMirrorCsv", [altered])])).toContain("CPI_GAP_MISMATCH: 2025 averages");
	});

	test("annualAverages: a year whose October was published after all is averaged over twelve months", () => {
		const filled = editedFixture((l) => (l.startsWith("2025-09") ? [l, "2025-10-01,324.461,0.0"] : l));
		const averages = callExport<Averages>(SCRIPT, "annualAverages", [callExport(SCRIPT, "parseMirrorCsv", [filled])]);
		expect(averages.years.find((y) => y.year === 2025)).toEqual({ year: 2025, value: 322.153, decimals: 3, months: 12, source: "computed" });
	});

	test("annualAverages: a series ending in December has no partial year", () => {
		const whole = editedFixture((l) => (l.startsWith("2026-") ? null : l));
		const averages = callExport<Averages>(SCRIPT, "annualAverages", [callExport(SCRIPT, "parseMirrorCsv", [whole])]);
		expect(averages.partial).toBeNull();
		expect(averages.years[averages.years.length - 1].year).toBe(2025);
	});

	test("renderTable: the header, the range and the partial year, and a bad retrieval date refused", () => {
		const averages = callExport(SCRIPT, "annualAverages", [callExport(SCRIPT, "parseMirrorCsv", [FIXTURE_TEXT])]);
		const text = callExport<string>(SCRIPT, "renderTable", [averages, { source: "a test", retrieved: "2026-10-01" }]);
		expect(text).toContain("export const CPI_MIN_YEAR = 1913;");
		expect(text).toContain("export const CPI_MAX_YEAR = 2026;");
		expect(text).toContain("1913: 9.9, 1914: 10.0,");
		expect(text).toContain("2025: 321.943, 2026: 331.180,");
		expect(text.endsWith("// END GENERATED BY scripts/build-cpi-table.mjs")).toBe(true);
		expect(text).not.toMatch(/—/);
		for (const retrieved of ["", "1 October 2026", "2026-10-01T00:00", "__proto__"]) {
			expect(refusal("renderTable", [averages, { source: "a test", retrieved }])).toContain("CPI_BAD_RETRIEVED");
		}
	});

	test("spliceTable: keeps what follows the marker, and refuses a file without one", () => {
		expect(callExport(SCRIPT, "spliceTable", ["NEW\n// END GENERATED BY scripts/build-cpi-table.mjs", "OLD\n// END GENERATED BY scripts/build-cpi-table.mjs\nrest\n"])).toBe(
			"NEW\n// END GENERATED BY scripts/build-cpi-table.mjs\nrest\n",
		);
		expect(refusal("spliceTable", ["NEW", "export const CPI_TABLE = {};\n"])).toContain("CPI_NO_MARKER");
	});

	test("parseBlsResponse: a failed request, a missing series and a hostile response are refused by name", () => {
		expect(refusal("parseBlsResponse", [{ status: "REQUEST_NOT_PROCESSED", message: ["daily threshold reached"] }])).toContain("CPI_BLS_REQUEST_FAILED: the BLS API did not succeed: daily threshold reached");
		expect(refusal("parseBlsResponse", [null])).toContain("CPI_BLS_REQUEST_FAILED");
		expect(refusal("parseBlsResponse", [{ status: "REQUEST_SUCCEEDED", Results: { series: [{ seriesID: "CUUR0000SA0E", data: [] }] } }])).toContain("CPI_BLS_NO_SERIES");
		expect(refusal("parseBlsResponse", [{ status: "REQUEST_SUCCEEDED", Results: { series: [{ seriesID: "CUUR0000SA0", data: [{ year: "1913", period: "M01", value: "-9.8" }] }] } }])).toContain("CPI_BAD_INDEX");
		expect(refusal("parseBlsResponse", [{ status: "REQUEST_SUCCEEDED", Results: { series: [{ seriesID: "CUUR0000SA0", data: [{ year: "1913", period: "M01", value: "9.8" }, { year: "1913", period: "M01", value: "9.8" }] }] } }])).toContain("CPI_DUPLICATE_MONTH");
		const proto = callExport<{ observations: Observation[] }>(SCRIPT, "parseBlsResponse", [{ status: "REQUEST_SUCCEEDED", Results: { series: [{ seriesID: "CUUR0000SA0", data: [{ year: "1913", period: "M01", value: "9.8" }, { year: "1913", period: "__proto__", value: "1" }, { year: "1913", period: "S01", value: "1" }] }] } }]);
		expect(proto.observations).toEqual([{ year: 1913, month: 1, value: 9.8, decimals: 1 }]);
	});
});

describe("a malformed or hostile CSV is refused by name", () => {
	test.each([
		["an empty file", "", "CPI_NO_DATA"],
		["whitespace only", "  \n\n", "CPI_NO_DATA"],
		["a header and no rows", "Date,Index,Inflation\n", "CPI_NO_DATA"],
		["the wrong header", "date,value\n1913-01-01,9.8\n", "CPI_CSV_BAD_HEADER"],
		["a fourth column", "Date,Index,Inflation,Extra\n", "CPI_CSV_BAD_HEADER"],
		["a row with too many cells", "Date,Index,Inflation\n1913-01-01,9.8,,x\n", "CPI_CSV_BAD_ROW"],
		["a row with too few", "Date,Index,Inflation\n1913-01-01\n", "CPI_CSV_BAD_ROW"],
		["a date that is not the first", "Date,Index,Inflation\n1913-01-15,9.8,\n", "CPI_BAD_DATE"],
		["a date before 1913", "Date,Index,Inflation\n1912-12-01,9.8,\n", "CPI_BAD_DATE"],
		["month 13", "Date,Index,Inflation\n1913-13-01,9.8,\n", "CPI_BAD_DATE"],
		["NaN", "Date,Index,Inflation\n1913-01-01,NaN,\n", "CPI_BAD_INDEX"],
		["a negative index", "Date,Index,Inflation\n1913-01-01,-9.8,\n", "CPI_BAD_INDEX"],
		["a zero index", "Date,Index,Inflation\n1913-01-01,0,\n", "CPI_BAD_INDEX"],
		["an empty index", "Date,Index,Inflation\n1913-01-01,,\n", "CPI_BAD_INDEX"],
		["markup in a cell", "Date,Index,Inflation\n1913-01-01,<script>alert(1)</script>,\n", "CPI_BAD_INDEX"],
		["digits from another script", "Date,Index,Inflation\n١٩١٣-01-01,9.8,\n", "CPI_BAD_DATE"],
		["a zero-width space in a date", "Date,Index,Inflation\n1913-​01-01,9.8,\n", "CPI_BAD_DATE"],
		["duplicate months", "Date,Index,Inflation\n1913-01-01,9.8,\n1913-01-01,9.9,\n", "CPI_DUPLICATE_MONTH"],
	])("%s", (_name, text, name) => {
		expect(refusal("parseMirrorCsv", [text])).toContain(`${name}:`);
	});

	test.each(PROTOTYPE_WORDS)("a %s column is refused as a header, not read as a property", (word) => {
		expect(refusal("parseMirrorCsv", [`Date,Index,${word}\n1913-01-01,9.8,\n`])).toContain("CPI_CSV_BAD_HEADER");
		expect(refusal("parseMirrorCsv", [`Date,Index,Inflation\n${word},9.8,\n`])).toContain("CPI_BAD_DATE");
		expect(refusal("parseMirrorCsv", [`Date,Index,Inflation\n1913-01-01,${word},\n`])).toContain("CPI_BAD_INDEX");
	});

	test("a huge file is refused before it is split", () => {
		const huge = `Date,Index,Inflation\n${"1913-01-01,9.8,\n".repeat(70_000)}`;
		expect(refusal("parseMirrorCsv", [huge])).toContain("CPI_SOURCE_TOO_LARGE: the source is larger than 1048576 bytes");
	});

	test("more rows than two centuries of months are refused, although the file is small", () => {
		const rows = Array.from({ length: 2_401 }, (_, i) => `${1913 + Math.floor(i / 12)}-${String((i % 12) + 1).padStart(2, "0")}-01,9.8,`);
		expect(refusal("parseMirrorCsv", [`Date,Index,Inflation\n${rows.join("\n")}\n`])).toContain("CPI_SOURCE_TOO_LARGE: the source has 2401 rows");
	});

	test("a value that is not text is refused", () => {
		expect(refusal("parseMirrorCsv", [null])).toContain("CPI_NO_DATA");
		expect(refusal("parseMirrorCsv", [{ length: 3 }])).toContain("CPI_NO_DATA");
	});

	test("CRLF line endings, a byte-order mark and no trailing newline read the same as the recording", () => {
		const crlf = `﻿${FIXTURE_TEXT.trimEnd().split("\n").join("\r\n")}`;
		expect(callExport(SCRIPT, "parseMirrorCsv", [crlf])).toEqual(callExport(SCRIPT, "parseMirrorCsv", [FIXTURE_TEXT]));
	});

	test("the command line refuses a bad file by name, exits 1 and leaves the output untouched", () => {
		const dir = tempTree({ "bad.csv": "Date,Index,Inflation\n1913-01-01,NaN,\n", "out.ts": "kept\n// END GENERATED BY scripts/build-cpi-table.mjs\n" });
		const result = runScript(SCRIPT, [`--from-csv=${path.join(dir, "bad.csv")}`, `--out=${path.join(dir, "out.ts")}`]);
		expect(result.status).toBe(1);
		expect(result.out).toContain("CPI_BAD_INDEX: line 2");
		expect(fs.readFileSync(path.join(dir, "out.ts"), "utf8")).toBe("kept\n// END GENERATED BY scripts/build-cpi-table.mjs\n");
	});

	test("--check fails on a table that has drifted from its source", () => {
		const dir = tempTree({ "out.ts": fs.readFileSync(TABLE_FILE, "utf8").replace("2025: 321.943", "2025: 322.2") });
		const result = runScript(SCRIPT, ["--check", `--out=${path.join(dir, "out.ts")}`]);
		expect(result.status).toBe(1);
		expect(result.out).toContain("is not what scripts/build-cpi-table.mjs generates. Run npm run data:cpi.");
	});
});

describe("both document passes agree", () => {
	test("the new years through parseDocument and evaluateDocument", () => {
		const { batch } = expectHonestDocument(
			[
				"start = 1965",
				"inflationAdjust($500, start, 2025)",
				"what is $500 in 1913 worth in 2026",
				"inflationAdjust($100, 1912, 2020)",
				"price = $100",
				"inflationAdjust(price, 2024, 2025)",
				"inflationAdjust($100, 2025, 2026) - $100",
			].join("\n"),
		);
		expect(batch).toEqual([
			"= 1,965",
			"= $5,110.21",
			"= $16,726.26",
			"ERROR Year 1912 is outside the bundled CPI table's range (1913-2026)",
			"= $100.00",
			"= $102.63",
			"= $2.87",
		]);
	});

	test("a CRLF document with a trailing newline", () => {
		const { batch } = expectHonestDocument("inflationAdjust($100, 1913, 1920)\r\ninflationAdjust($100, 1920, 1933)\r\n");
		expect(batch.slice(0, 2)).toEqual(["= $202.02", "= $64.50"]);
	});
});

describe("adversarial lines", () => {
	test("prototype words where a year goes are honest, and Object.prototype is unchanged", () => {
		expectPrototypeUntouched(() => {
			for (const word of PROTOTYPE_WORDS) {
				expectHonestLine(`what is $100 from ${word}`, { engine: engine2026() });
				expectHonestLine(`what was $500 worth in ${word}`, { engine: engine2026() });
				expectHonestLine(`inflationAdjust($100, ${word}, 2020)`);
			}
		});
	});

	test("numeric edges where a year goes are honest, and never a number for a year outside 1913 to 2026", () => {
		for (const line of fill("inflationAdjust($100, X, 2020)", NUMERIC_EDGES)) expectHonestLine(line, { allowNaN: true });
		for (const line of fill("what was $500 worth in X", NUMERIC_EDGES)) expectHonestLine(line, { engine: engine2026(), allowNaN: true });
		for (const year of ["0", "-1913", "2026.5e3", "2^53", "1e308"]) {
			expect({ year, code: code(`inflationAdjust($100, ${year}, 2020)`) }).toEqual({ year, code: "INFLATION_YEAR_OUT_OF_RANGE" });
		}
		// A fraction is not a year at all, in range or not (see FoundBug_inflationYear.spec.ts).
		expect(code("inflationAdjust($100, 1912.999, 2020)")).toBe("INFLATION_EXPECTED_YEAR");
	});

	test("text edges around the form are honest", () => {
		for (const text of TEXT_EDGES) expectHonestLine(`what was $500 worth in 1965 ${text}`, { engine: engine2026() });
	});

	test("a long run of inflation lines stays within its budget", () => {
		const doc = Array.from({ length: 500 }, (_, i) => `inflationAdjust($100, ${1913 + (i % 114)}, 2026)`).join("\n");
		expectHonestDocument(doc, { budgetMs: 20_000 });
	});

	test("realistic breakage: a typo, pounds, a bare number and a value from the line above", () => {
		expect(expectHonestLine("what was $500 worth in 1965x", { engine: engine2026() }).kind).not.toBe("value");
		// Pounds read the UK index since #756; a bare number is still refused.
		expect(shown("what was £500 worth in 1965")).toBe("= £17.92");
		expect(code("what was 500 worth in 1965")).toBe("INFLATION_NO_INDEX");
		const { batch } = expectHonestDocument("year = 1913\ninflationAdjust($1, year, year + 113)");
		expect(batch[1]).toBe("= $33.45");
	});
});
