/**
 * U.S. CPI-U (Consumer Price Index for All Urban Consumers, U.S. city
 * average, all items, not seasonally adjusted, 1982-84=100) annual averages.
 *
 * Generated by `npm run data:cpi` (scripts/build-cpi-table.mjs). Do not edit
 * the part above the END GENERATED line by hand: change the script or its
 * source and run it again.
 *
 * Source: U.S. Bureau of Labor Statistics, series CUUR0000SA0, monthly values
 * as mirrored by the Frictionless Data cpi-us dataset
 * (github.com/datasets/cpi-us, data/cpiai.csv, from
 * raw.githubusercontent.com), recorded in scripts/fixtures/cpi/cpiai.csv.
 * Retrieved 2026-10-01.
 *
 * Method: each year is the mean of its published monthly values, rounded to
 * the precision BLS publishes them to (one decimal before 2007, three from
 * 2007), which is how BLS derives its annual average; a published annual
 * average (BLS period M13) is used as it stands where the source has one.
 * October 2025 was never published (data unavailable due to the 2025 lapse in
 * appropriations), so 2025 is the mean of its 11 published months, 321.943,
 * which is the annual average BLS published for it.
 * 2026 is partial: it averages the 7 months published so far, January to July,
 * and moves as the rest are published.
 *
 * Coverage: 1913-2026 inclusive (114 years). A year outside it
 * produces `INFLATION_YEAR_OUT_OF_RANGE` rather than an extrapolation. The
 * index is the US one, so only an amount in US dollars is adjusted with it
 * (see `InflationAmount.ts`). It is not authoritative for contracts, tax or
 * cost-of-living escalation: consult bls.gov/cpi for those.
 */
export const CPI_TABLE: Readonly<Record<number, number>> = {
  1913: 9.9, 1914: 10.0, 1915: 10.1, 1916: 10.9, 1917: 12.8,
  1918: 15.0, 1919: 17.3, 1920: 20.0, 1921: 17.9, 1922: 16.8,
  1923: 17.1, 1924: 17.1, 1925: 17.5, 1926: 17.7, 1927: 17.4,
  1928: 17.2, 1929: 17.2, 1930: 16.7, 1931: 15.2, 1932: 13.6,
  1933: 12.9, 1934: 13.4, 1935: 13.7, 1936: 13.9, 1937: 14.4,
  1938: 14.1, 1939: 13.9, 1940: 14.0, 1941: 14.7, 1942: 16.3,
  1943: 17.3, 1944: 17.6, 1945: 18.0, 1946: 19.5, 1947: 22.3,
  1948: 24.0, 1949: 23.8, 1950: 24.1, 1951: 26.0, 1952: 26.6,
  1953: 26.8, 1954: 26.9, 1955: 26.8, 1956: 27.2, 1957: 28.1,
  1958: 28.9, 1959: 29.2, 1960: 29.6, 1961: 29.9, 1962: 30.3,
  1963: 30.6, 1964: 31.0, 1965: 31.5, 1966: 32.5, 1967: 33.4,
  1968: 34.8, 1969: 36.7, 1970: 38.8, 1971: 40.5, 1972: 41.8,
  1973: 44.4, 1974: 49.3, 1975: 53.8, 1976: 56.9, 1977: 60.6,
  1978: 65.2, 1979: 72.6, 1980: 82.4, 1981: 90.9, 1982: 96.5,
  1983: 99.6, 1984: 103.9, 1985: 107.6, 1986: 109.6, 1987: 113.6,
  1988: 118.3, 1989: 124.0, 1990: 130.7, 1991: 136.2, 1992: 140.3,
  1993: 144.5, 1994: 148.2, 1995: 152.4, 1996: 156.9, 1997: 160.5,
  1998: 163.0, 1999: 166.6, 2000: 172.2, 2001: 177.1, 2002: 179.9,
  2003: 184.0, 2004: 188.9, 2005: 195.3, 2006: 201.6, 2007: 207.342,
  2008: 215.303, 2009: 214.537, 2010: 218.056, 2011: 224.939, 2012: 229.594,
  2013: 232.957, 2014: 236.736, 2015: 237.017, 2016: 240.007, 2017: 245.120,
  2018: 251.107, 2019: 255.657, 2020: 258.811, 2021: 270.970, 2022: 292.655,
  2023: 304.702, 2024: 313.689, 2025: 321.943, 2026: 331.180,
} as const;

/** Earliest year this table has data for, used for range-check error messages. */
export const CPI_MIN_YEAR = 1913;
/**
 * Most recent year in {@link CPI_TABLE}.
 *
 * A request beyond this is rejected rather than extrapolated, since inflation
 * past the last published figure is a forecast and not a conversion.
 */
export const CPI_MAX_YEAR = 2026;

/** The latest year when it stops before December, and the months it averages (one-based). */
export const CPI_PARTIAL_YEAR: { readonly year: number; readonly months: readonly number[] } | null = { year: 2026, months: [1, 2, 3, 4, 5, 6, 7] };
// END GENERATED BY scripts/build-cpi-table.mjs

/** Look up the CPI-U annual average for `year`, or `undefined` if out of range. */
export function getCpi(year: number): number | undefined {
  return CPI_TABLE[Math.trunc(year)];
}

/**
 * Ratio to multiply a `fromYear` dollar amount by to express it in
 * `toYear` dollars: `amount(toYear) = amount(fromYear) * inflationRatio(fromYear, toYear)`.
 *
 * @returns `undefined` if either year is outside the table's range, or if
 *   `fromYear`'s CPI is exactly 0 (never true for real data, guarded anyway
 *   since it would otherwise divide by zero).
 */
export function inflationRatio(fromYear: number, toYear: number): number | undefined {
  const fromCpi = getCpi(fromYear);
  const toCpi = getCpi(toYear);
  if (fromCpi === undefined || toCpi === undefined || fromCpi === 0) return undefined;
  return toCpi / fromCpi;
}

/**
 * Adjust `amount` from `fromYear` dollars to `toYear` dollars using the CPI
 * table above.
 *
 * @returns `undefined` if either year is out of the table's covered range
 *   (caller should surface this as a clear error, not a silently wrong number).
 */
export function adjustForInflation(amount: number, fromYear: number, toYear: number): number | undefined {
  const ratio = inflationRatio(fromYear, toYear);
  if (ratio === undefined) return undefined;
  return amount * ratio;
}
