/**
 * Euro-area HICP (harmonised index of consumer prices, euro area changing
 * composition, overall index, 2015 = 100) annual averages.
 *
 * Generated by `npm run data:cpi` (scripts/build-euro-hicp-table.mjs). Do
 * not edit the part above the END GENERATED line by hand: change the script
 * or its source and run it again.
 *
 * Source: Eurostat, published by the European Central Bank as series
 * ICP.M.U2.N.000000.4.INX, the ECB data API's CSV of the series
 * (data-api.ecb.europa.eu/service/data/ICP/M.U2.N.000000.4.INX?format=csvdata)
 * as archived in the public repository github.com/MaxGhenis/expectations
 * (data/raw/ecb_ea_hicp_index_monthly.csv, retrieved by that project on
 * 2026-09-05, SHA-256
 * 9bfa365fe6dd664c75f90f271821011bfb8cc5a7e1d0b181850951529e225b88 as archived
 * there, line endings since normalised to LF), recorded in
 * scripts/fixtures/cpi/ecb-icp-hicp-euro-area.csv, since the ECB and Eurostat
 * hosts were not reachable from the build. Retrieved 2026-10-01.
 *
 * Method: each year is the mean of its twelve monthly values, rounded to the
 * two decimals the series is published to, which is how Eurostat derives
 * its annual average index (prc_hicp_aind, INX_A_AVG).
 * Every year is complete. The series' last month is December 2025: the ECB
 * discontinued this dataset in February 2026, when Eurostat's methodological
 * changes to the HICP took effect, and its replacement is not joined on.
 *
 * Coverage: 1996-2025 inclusive (30 years). A year outside it produces
 * `INFLATION_YEAR_OUT_OF_RANGE` rather than an extrapolation, and so does a
 * year before the euro began in 1999 (see `EURO_FIRST_YEAR` below). Only an
 * amount in euros is adjusted with it (see `PriceIndices.ts`). It is not
 * authoritative for contracts, tax or cost-of-living escalation: consult
 * Eurostat for those.
 */
export const EURO_HICP_TABLE: Readonly<Record<number, number>> = {
  1996: 71.74, 1997: 72.87, 1998: 73.67, 1999: 74.48, 2000: 76.05,
  2001: 77.83, 2002: 79.58, 2003: 81.24, 2004: 82.98, 2005: 84.79,
  2006: 86.64, 2007: 88.49, 2008: 91.38, 2009: 91.65, 2010: 93.14,
  2011: 95.66, 2012: 98.05, 2013: 99.38, 2014: 99.81, 2015: 100.00,
  2016: 100.23, 2017: 101.78, 2018: 103.56, 2019: 104.80, 2020: 105.06,
  2021: 107.78, 2022: 116.82, 2023: 123.15, 2024: 126.07, 2025: 128.75,
} as const;

/** Earliest year this table has data for. */
export const EURO_HICP_MIN_YEAR = 1996;
/** Most recent year in {@link EURO_HICP_TABLE}; a later one is refused rather than extrapolated. */
export const EURO_HICP_MAX_YEAR = 2025;

/** The latest year when it stops before December, and the months it averages (one-based). */
export const EURO_HICP_PARTIAL_YEAR: { readonly year: number; readonly months: readonly number[] } | null = null;
// END GENERATED BY scripts/build-euro-hicp-table.mjs

/**
 * The first year an amount in euros can be adjusted from or to. The euro-area
 * index starts in 1996, but the euro itself began on 1 January 1999 (as money
 * of account; its notes and coins followed in 2002), so an amount in euros from
 * 1996 to 1998 would be a sum in a national currency converted at a rate fixed
 * afterwards. Those years are refused by name rather than answered as if the
 * euro had existed (#756).
 */
export const EURO_FIRST_YEAR = 1999;
