/**
 * The bundled price indices, one per currency, and the lookups the inflation
 * forms share (#756).
 *
 * An inflation adjustment reads a consumer price index: a record of what a
 * typical basket of shopping cost in each year. Each index says what one
 * currency bought, so the amount's currency picks the index: US dollars read
 * the BLS CPI-U (`CpiTable.ts`), pounds sterling the ONS long-term indicator
 * CDKO (`UkCpiTable.ts`), and euros the euro-area HICP (`EuroHicpTable.ts`).
 * Every table is generated by a script from a recorded source and states it.
 *
 * A year outside an index is refused by name with that index's range, never
 * extrapolated. The euro has a second boundary inside its index's range: the
 * HICP starts in 1996, the euro in 1999, so a euro amount from 1996 to 1998 is
 * refused with the reason.
 */

import { CPI_TABLE, CPI_MIN_YEAR, CPI_MAX_YEAR } from "./CpiTable";
import { UK_CPI_TABLE, UK_CPI_MIN_YEAR, UK_CPI_MAX_YEAR } from "./UkCpiTable";
import { EURO_HICP_TABLE, EURO_HICP_MIN_YEAR, EURO_HICP_MAX_YEAR, EURO_FIRST_YEAR } from "./EuroHicpTable";
import { numberText } from "@solve-js/utilities/Number";

/** One bundled index: the currency it measures, its table, and the years an amount can be adjusted between. */
export interface PriceIndex {
  /** The ISO code of the currency the index measures. */
  readonly currency: string;
  /** The index in the reader's words, for messages: `the UK price index (ONS CDKO)`. */
  readonly name: string;
  /** Annual figures by year. */
  readonly table: Readonly<Record<number, number>>;
  /** The first year an amount can be adjusted from or to. */
  readonly firstYear: number;
  /** The last year an amount can be adjusted from or to. */
  readonly lastYear: number;
  /** The sentence for a year outside {@link firstYear} to {@link lastYear}. */
  readonly yearOutside: (year: number) => string;
}

/** The US index: BLS CPI-U, series CUUR0000SA0 (#700). */
export const US_PRICE_INDEX: PriceIndex = Object.freeze({
  currency: "USD",
  name: "the US consumer price index (BLS CPI-U)",
  table: CPI_TABLE,
  firstYear: CPI_MIN_YEAR,
  lastYear: CPI_MAX_YEAR,
  yearOutside: (year: number) => `Year ${numberText(year)} is outside the bundled CPI table's range (${CPI_MIN_YEAR}-${CPI_MAX_YEAR})`,
});

/** The UK index: the ONS long-term indicator of consumer prices, series CDKO. */
export const UK_PRICE_INDEX: PriceIndex = Object.freeze({
  currency: "GBP",
  name: "the UK price index (ONS CDKO)",
  table: UK_CPI_TABLE,
  firstYear: UK_CPI_MIN_YEAR,
  lastYear: UK_CPI_MAX_YEAR,
  yearOutside: (year: number) => `Year ${numberText(year)} is outside the bundled UK price index's range (${UK_CPI_MIN_YEAR}-${UK_CPI_MAX_YEAR})`,
});

/** The euro-area index: Eurostat's HICP for the euro area, from 1999 when the euro began. */
export const EURO_PRICE_INDEX: PriceIndex = Object.freeze({
  currency: "EUR",
  name: "the euro-area price index (Eurostat HICP)",
  table: EURO_HICP_TABLE,
  firstYear: Math.max(EURO_FIRST_YEAR, EURO_HICP_MIN_YEAR),
  lastYear: EURO_HICP_MAX_YEAR,
  yearOutside: (year: number) =>
    year < EURO_FIRST_YEAR
      ? `Year ${numberText(year)} is before the euro began in ${EURO_FIRST_YEAR}, so there is no amount in euros from then to adjust (the euro-area price index itself starts in ${EURO_HICP_MIN_YEAR})`
      : `Year ${numberText(year)} is outside the bundled euro-area price index's range (${Math.max(EURO_FIRST_YEAR, EURO_HICP_MIN_YEAR)}-${EURO_HICP_MAX_YEAR}): the series it is built from ends with ${EURO_HICP_MAX_YEAR}, so name a year up to ${EURO_HICP_MAX_YEAR} to adjust to`,
});

/** The indices by currency code, with no prototype, so a hostile code finds nothing. */
const BY_CURRENCY: Readonly<Record<string, PriceIndex>> = Object.freeze(
  Object.assign(Object.create(null) as Record<string, PriceIndex>, {
    USD: US_PRICE_INDEX,
    GBP: UK_PRICE_INDEX,
    EUR: EURO_PRICE_INDEX,
  }),
);

/** The currencies an index is bundled for, in the order messages list them. */
export const INDEXED_CURRENCIES: readonly string[] = Object.freeze(["USD", "GBP", "EUR"]);

/**
 * The bundled index for a currency, or undefined when none is bundled.
 *
 * @param currency - An ISO currency code, as a money Value's unit carries it.
 */
export function priceIndexFor(currency: string): PriceIndex | undefined {
  if (typeof currency !== "string" || !Object.prototype.hasOwnProperty.call(BY_CURRENCY, currency)) return undefined;
  return BY_CURRENCY[currency];
}

/**
 * The index's figure for a year, or undefined outside the years an amount can
 * be adjusted between. A fractional year reads its whole year, as the US table
 * always has (`getCpi(1913.9)` is 1913's figure).
 */
export function indexFigure(index: PriceIndex, year: number): number | undefined {
  if (!Number.isFinite(year)) return undefined;
  const whole = Math.trunc(year);
  if (whole < index.firstYear || whole > index.lastYear || !Object.prototype.hasOwnProperty.call(index.table, whole)) return undefined;
  return index.table[whole];
}

/**
 * The ratio to multiply a `fromYear` amount by to express it in `toYear`
 * money, or undefined when either year is outside the index (or a figure is
 * zero, which no real figure is).
 */
export function indexRatio(index: PriceIndex, fromYear: number, toYear: number): number | undefined {
  const from = indexFigure(index, fromYear);
  const to = indexFigure(index, toYear);
  if (from === undefined || to === undefined || from === 0) return undefined;
  return to / from;
}

/**
 * The first of two years the index cannot read, for the refusal, or undefined
 * when it reads both.
 */
export function yearOutsideIndex(index: PriceIndex, fromYear: number, toYear: number): number | undefined {
  if (indexFigure(index, fromYear) === undefined) return fromYear;
  if (indexFigure(index, toYear) === undefined) return toYear;
  return undefined;
}
