/**
 * Fails when a documentation page exists that the sidebar never mentions.
 *
 * The sidebar used to be autogenerated per directory, which meant it could not
 * miss a page and could not be in a sensible order either: alphabetical put the
 * bytecode virtual machine ahead of the overview that introduces it. Listing
 * the pages explicitly fixes the order and reintroduces the failure mode
 * autogeneration was protecting against, where somebody adds a page and it is
 * reachable only by search.
 *
 * This is the other half of that trade. It reads the slugs out of the Astro
 * config and the pages off disk, and complains about either direction: a page
 * with no sidebar entry, and a sidebar entry with no page.
 *
 * Text matching rather than importing the config, deliberately. The config
 * imports Astro integrations and a Shiki grammar, so loading it here would mean
 * a working docs install just to run a lint.
 *
 * Usage:
 *   node scripts/check-sidebar.mjs
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONFIG = path.join(ROOT, "docs/astro.config.mjs");
const CONTENT = path.join(ROOT, "docs/src/content/docs");

/**
 * Every page slug on disk, in Starlight's form.
 *
 * `index` is the landing page, which is reached by the wordmark rather than by
 * the sidebar, so it is not expected to appear.
 *
 * @param {string} dir - Directory to walk.
 * @param {string} prefix - Slug prefix accumulated so far.
 * @returns {string[]} Slugs.
 */
function pageSlugs(dir, prefix = "") {
	const out = [];

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			out.push(...pageSlugs(full, `${prefix}${entry.name}/`));
			continue;
		}
		if (!/\.mdx?$/.test(entry.name)) continue;

		const slug = prefix + entry.name.replace(/\.mdx?$/, "");
		if (slug === "index") continue;
		out.push(slug);
	}

	return out;
}

const config = fs.readFileSync(CONFIG, "utf8");
const listed = new Set(
	Array.from(config.matchAll(/slug:\s*"([^"]+)"/g)).map((match) => match[1]),
);
const onDisk = pageSlugs(CONTENT);

const missing = onDisk.filter((slug) => !listed.has(slug)).sort();
const orphaned = [...listed].filter((slug) => !onDisk.includes(slug)).sort();

if (missing.length === 0 && orphaned.length === 0) {
	console.log(`Sidebar covers all ${onDisk.length} documentation page(s).`);
	process.exit(0);
}

if (missing.length > 0) {
	console.error("These pages exist but are not in the sidebar:");
	for (const slug of missing) console.error(`  ${slug}`);
	console.error("Add them to `sidebar` in docs/astro.config.mjs, in reading order.");
}

if (orphaned.length > 0) {
	console.error("These sidebar entries have no page:");
	for (const slug of orphaned) console.error(`  ${slug}`);
}

process.exit(1);
