/**
 * The CPI table, checked against the published series it is built from.
 *
 * The table is generated by `scripts/build-cpi-table.mjs` from BLS series
 * CUUR0000SA0 (#700), every year from 1913. It used to hold figures recalled
 * from general knowledge, from 1970, with 2025 and 2026 chained from an IMF
 * series; those were 322.2 and 332.7 against the published 321.943 and the
 * partial-year mean of 331.180.
 *
 * The anchors below are BLS's own published annual averages (period M13), so
 * a table built wrongly from the monthly values, or edited by hand, fails
 * here. `Issue700_cpiTableFromBls.spec.ts` checks the generator itself.
 *
 * These are fixed numbers rather than a live fetch on purpose. A test that
 * calls a network service is a test that fails when the service is down, and
 * the point here is to catch the table being wrong, not to monitor somebody's
 * uptime.
 */

import { describe, expect, test } from "@jest/globals";
import { CPI_TABLE, CPI_MIN_YEAR, CPI_MAX_YEAR, CPI_PARTIAL_YEAR } from "@solve-js/packages/finance/data/CpiTable";

/** Cumulative inflation between two years, as the engine computes it. */
function ratio(from: number, to: number): number {
	return CPI_TABLE[to] / CPI_TABLE[from];
}

describe("against the BLS published annual averages", () => {
	test.each([
		[1913, 9.9],
		[1920, 20.0],
		[1933, 12.9],
		[1965, 31.5],
		[1970, 38.8],
		[1980, 82.4],
		[2000, 172.2],
		[2008, 215.303],
		[2009, 214.537],
		[2020, 258.811],
		[2021, 270.97],
		[2022, 292.655],
		[2023, 304.702],
		[2024, 313.689],
		[2025, 321.943],
	])("%i is %d", (year, published) => {
		expect(CPI_TABLE[year]).toBe(published);
	});

	test("2025 is the published figure although October 2025 was never collected", () => {
		// BLS averaged the eleven months it has; the generator does the same and
		// refuses the build if the result differs from this figure.
		expect(CPI_TABLE[2025]).toBe(321.943);
	});

	test("the current year is partial and says which months it averages", () => {
		expect(CPI_PARTIAL_YEAR).toEqual({ year: CPI_MAX_YEAR, months: [1, 2, 3, 4, 5, 6, 7] });
		expect(CPI_TABLE[2026]).toBe(331.18);
	});
});

describe("the table's shape", () => {
	test("it runs from 1913, the first year of the series, with every year present", () => {
		expect(CPI_MIN_YEAR).toBe(1913);
		const missing: number[] = [];
		for (let year = CPI_MIN_YEAR; year <= CPI_MAX_YEAR; year++) {
			if (CPI_TABLE[year] === undefined) missing.push(year);
		}
		expect(missing).toEqual([]);
		expect(Object.keys(CPI_TABLE)).toHaveLength(CPI_MAX_YEAR - CPI_MIN_YEAR + 1);
	});

	test("the index fell or stood still in exactly the years it really did", () => {
		// The 1920s and early 1930s deflation, 1938 to 1939, 1949, 1955 and
		// 2009. 1924 and 1929 are flat at one decimal, as BLS publishes them.
		const notRising: number[] = [];
		for (let year = CPI_MIN_YEAR + 1; year <= CPI_MAX_YEAR; year++) {
			if (CPI_TABLE[year] <= CPI_TABLE[year - 1]) notRising.push(year);
		}
		expect(notRising).toEqual([1921, 1922, 1924, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1938, 1939, 1949, 1955, 2009]);
	});

	test("the only years that move by more than 15% are the ones around the First World War", () => {
		// A fat-fingered digit shows up as a jump no real year had.
		const large: string[] = [];
		for (let year = CPI_MIN_YEAR + 1; year <= CPI_MAX_YEAR; year++) {
			const change = (ratio(year - 1, year) - 1) * 100;
			if (Math.abs(change) > 15) large.push(`${year}: ${change.toFixed(1)}%`);
		}
		expect(large).toEqual(["1917: 17.4%", "1918: 17.2%", "1919: 15.3%", "1920: 15.6%"]);
	});
});

describe("known anchors", () => {
	test("a dollar in 1970 buys what about eight and a half do in 2026", () => {
		expect(ratio(1970, 2026)).toBeCloseTo(8.536, 3);
	});

	test("prices roughly doubled across the 1970s", () => {
		expect(ratio(1970, 1980)).toBeCloseTo(2.124, 3);
	});

	test("2024 to 2025 is the 2.6% the published averages give", () => {
		expect((ratio(2024, 2025) - 1) * 100).toBeCloseTo(2.63, 2);
	});
});
